### ISSUE TITLE
VS script previews fine but crashes encoder

### ISSUE THREAD

**Issue by Statick** [staxrip/staxrip#1146]
I've been using staxrip for years but only very recently have I switched from avisynth to vapoursynth, and having never used python before it's a bit of a learning curve. so it's quite possible I'm missing something stupid here. the short version is my VS script previews fine and everything looks as expected, but one bit of the code crashes when I actually run the encoder, yet I can't see any reason for this as the code looks fine, and works fine in the preview window without any problems or unexpected behaviours at all

I've put my code into a couple of functions in a separate .py script which I'm importing into staxrip, so I can call the function from staxrip with a few parameters easily, so it's possible I'm doing something wrong here. it's a simple script that reads a text file of frame overrides so I can specify how certain frames, or ranges of frames, get treated with deinterlace functions, it uses FrameEval so in the main function the current frame is "n" and I simply compare that against the contents of the text file, and return either the input clip or a given deinterlaced clip depending on if a match is found. I've got my .py script (named AdaptDeint.py) in the Apps\Plugins\VS\Scripts folder, and I'm importing it just before calling it in staxrip 

```
import AdaptDeint as ad
deint = core.znedi3.nnedi3(clip, field=1, nsize=6, nns=4, qual=2)
clip = ad.AdaptDeint(clip, deint, thresh=10, mapping=r"%source_dir%mapping.txt", show=showmask)
```

it uses tdeintmod which doesn't get auto loaded so I've added a loader for that at "code inserted at the top of scripts"
`core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\TDeintMod\TDeintMod.dll", altsearchpath=True)
`

the specific bit of code I'm having problems with is when the text file parser reads a line that specifies there's a range of frames to be treated. I've commented out much of the actual code at this point so that it just returns the input clip with a message overlayed "debug" so I can see if it works or not. I will attach the full code and log files at the end but here's the main problem bit : 

```
    output = clip
    message = "untouched frame"
    with open(mapping) as f:
        for line in f:
            l = line.strip()
            space = l.find(" ")
            start = l[:space]

            # range is specified as [500 1000] 
            if l.startswith("["):
                firstframe = start[1:]
                if not firstframe.isnumeric():
                    continue
                    
                bracket = l.find("]")
                if bracket == -1:
                    continue
                    
                lastframe = l[space + 1:bracket]
                if not lastframe.isnumeric():
                    continue
                    
                firstnum = int(firstframe)
                lastnum = int(lastframe)
                if lastnum < firstnum:
                    continue

                # this crashes the encoder as soon as "n >= firstnum" is true
                if n >= firstnum and n <= lastnum:
                    output = clip
                    message = "debug"
                    break
    f.close()
    return output.text.Text(message)

```

if I preview this it works fine and when the range (say, 3500 - 4000) is reached, the "debug" message appears on the clip in the preview window. but when I run the encoder, it will successfully encode the first 3499 frames and then crash when it reaches frame 3500 and "if n >= firstnum" is true. the error message given in the log is generic and simply says 

```
[vapoursynth @ 000002693c4ea040] Error getting frame: 
Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2
[in#0/vapoursynth @ 000002693c4e9ec0] Error during demuxing: Generic error in an external library
[in#0/vapoursynth @ 000002693c4e9ec0] Error retrieving a packet from demuxer: Generic error in an external library
```

if I replace "firstnum" and "lastnum" with hard coded integers, it works fine in the encoder without crashing
```
                # this works fine without crashing
                if n >= 2500 and n <= 3000:
                    output = clip
                    message = "debug"
                    break
```

this suggests to me that it could be a problem with "lastnum" which only becomes apparent when "if n >= firstnum". however if I replace "firstnum" with a hard coded integer and leave "lastnum" in place ,this also works fine without crashing

```
                if n >= 2500 and n <= lastnum:
                    output = clip
                    message = "debug"
                    break
```
so at this point it's not really making much sense to me. the only version of the code that actually causes the crash is when it includes "if n >= firstnum" yet it only crashes when that is actually true, which suggests it had to have successfully evaluated that. also that it can crash the encoder yet preview fine also doesn't make sense to me

**Comment by Statick** [comment]
my full imported script
"AdaptDeint.py"

```
import vapoursynth as vs
import os
import functools

MODULE_NAME = 'AdaptDeint'

def AdaptDeint(clip, deint, thresh=10, mapping="", show=False):
    core = vs.core
    mask = GetMask(clip, thresh=thresh)
    
    if mapping == "":
        if show==True:
            return core.std.Merge(clip, mask)
        else:
            return core.std.MaskedMerge(clip, deint, mask)
            
    if not os.path.isfile(mapping):
        raise vs.Error("Mapping file not found")
    
    return core.std.FrameEval(clip, functools.partial(MapFrame, clip=clip, deint=deint, mapping=mapping, thresh=thresh, show=show))
    
    
def MapFrame(n, clip, deint, mapping="", thresh=10, show=False):
    core = vs.core
    output = clip
    mask = GetMask(clip, thresh=thresh)
    message = "untouched frame"
    attr = ""

    with open(mapping) as f:
        for line in f:
            l = line.strip()
            space = l.find(" ")
                
            if space == -1:
                l = l.strip()
                if l.isnumeric():
                    frame = int(l)
                    if frame == n:
                        mask = GetMask(clip, thresh=thresh)
                        output = core.std.MaskedMerge(clip, deint, mask)
                        message = "single adaptive frame"
                        break
                else:
                    continue
                
            start = l[:space]
            if start.lower().startswith("default"):
                attr = l[space + 1:].strip()
                if attr.isnumeric():
                    thresh = int(attr)
                    mask = GetMask(clip, thresh=thresh)
                    continue
                     
            if start.isnumeric():
                frame = int(start)
                if frame == n:

                    attr = l[space + 1:].strip()                   
                    if attr == "+":
                        output = deint
                        message = "single fully decombed frame"
                        break
                    
                    if attr.isnumeric():
                        th = int(attr)
                        mask = GetMask(clip, thresh=th)
                        output = core.std.MaskedMerge(clip, deint, mask)
                        message = "single adaptive frame (thresh " + str(th) + ")"
                        break
                        
                    mask = GetMask(clip, thresh=thresh)
                    output = core.std.MaskedMerge(clip, deint, mask)
                    message = "single adaptive frame"
                    break

            if l.startswith("["):
                firstframe = start[1:]
                if not firstframe.isnumeric():
                    continue
                    
                bracket = l.find("]")
                if bracket == -1:
                    continue
                    
                lastframe = l[space + 1:bracket]
                if not lastframe.isnumeric():
                    continue
                    
                firstnum = int(firstframe)
                lastnum = int(lastframe)
                if lastnum < firstnum:
                    continue

                if n >= firstnum and n <= lastnum:
                    output = clip
                    message = "debug"
                    break

                '''
                if n >= first and n <= last:
                    attr = l[bracket + 1:].strip()
                    if attr == "+":
                        output = deint
                        message = "range of fully decombed frames"
                        break
                        
                    if attr.isnumeric():
                        th = int(attr)
                        mask = GetMask(clip, thresh=th)
                        output = core.std.MaskedMerge(clip, deint, mask)
                        message = "range of adaptive frames (thresh " + str(th) + ")"
                        break
                        
                    mask = GetMask(clip, thresh=thresh)
                    output = core.std.MaskedMerge(clip, deint, mask)
                    message = "range of adaptive frames"
                    break
                '''
                
                output = clip
                message = "untouched frame"
    f.close()
    if show:
        return core.std.Merge(output, mask).text.Text(message)
    else:
        return output.text.Text(message)
    
                
def GetMask(clip, thresh=10):
    core = vs.core
    mask = core.tdm.TDeintMod(clip, order=1, athresh=thresh, show=True)
    mask = core.std.Convolution(mask, [0,2,0,0,2,0,0,2,0]).std.Deflate().std.BinarizeMask(threshold=70).std.Maximum().std.Maximum().std.BoxBlur()
    return mask
   
```



and the logfile from staxrip


```
------------------------- System Environment -------------------------

StaxRip    : v2.29.0
Windows    : Windows 10 Pro 22H2 2009 (19041.1.amd64fre.vb_release.191206-1406)
Language   : English (United Kingdom)
CPU        : Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
RAM        : 16GB
GPU        : NVIDIA GeForce GTX 1660, Microsoft Remote Display Adapter, Intel(R) HD Graphics 630
Resolution : 1920 x 1080
DPI        : 120
Code Page  : 65001

---------------------------- Configuration ----------------------------

Template                : DVD to FFV1
Video Encoder           : ffmpegEnc
Video Encoder Profile   : ffmpeg | FFV1
Container/Muxer Profile : MKV (mkvmerge)

------------------------- VapourSynth Script -------------------------

import os, sys
import vapoursynth as vs
core = vs.core
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Settings\Plugins\VapourSynth\bm3dcuda.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Settings\Plugins\VapourSynth\LGhost.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Settings\Plugins\VapourSynth\libtivtc.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Settings\Plugins\VapourSynth\RemapFramesVapoursynth.dll", altsearchpath=True)

sys.path.append(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\Scripts")
import importlib.machinery
mvsfunc = importlib.machinery.SourceFileLoader('mvsfunc', r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\Scripts\mvsfunc.py").load_module()
adjust = importlib.machinery.SourceFileLoader('adjust', r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\Scripts\adjust.py").load_module()
havsfunc = importlib.machinery.SourceFileLoader('havsfunc', r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\Scripts\havsfunc.py").load_module()
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\d2vsource\d2vsource.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\AddGrain\AddGrain.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\AWarpSharp2\libawarpsharp2.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\CAS\CAS.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\CTMF\CTMF.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\DCTFilter\DCTFilter.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\Deblock\Deblock.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\DFTTest\DFTTest.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\EEDI2\EEDI2.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\EEDI3m\EEDI3m.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\FFT3DFilter\fft3dfilter.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\Dual\flash3kyuu_deband\flash3kyuu_deband.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\FluxSmooth\libfluxsmooth.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\fmtconv\fmtconv.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\HQDN3D\libhqdn3d.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\Dual\KNLMeansCL\KNLMeansCL.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\MiscFilters\MiscFilters.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\BM3D\BM3D.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\mvtools\libmvtools.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\nnedi3\libnnedi3.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\nnedi3\NNEDI3CL.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\RemoveGrainVS\RemoveGrainVS.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\Sangnom\libsangnom.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\scenechange\scenechange.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\SVPFlow\svpflow1_vs64.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\SVPFlow\svpflow2_vs64.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\TTempSmooth\TTempSmooth.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\nnedi3\vsznedi3.dll", altsearchpath=True)
core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.29.0-x64\Apps\Plugins\VS\TDeintMod\TDeintMod.dll", altsearchpath=True)

clip = core.d2v.Source(r"E:\video work\rips\farscape\Farscape 1x01 - Premiere\Farscape 1x01 - Premiere.d2v")
showmask = False
import AdaptDeint as ad
deint = core.znedi3.nnedi3(clip, field=1, nsize=6, nns=4, qual=2)
clip = ad.AdaptDeint(clip, deint, thresh=10, mapping=r"E:\video work\rips\farscape\Farscape 1x01 - Premiere\mapping.txt", show=showmask)
clip = havsfunc.Vinverse2(clip)
clip.set_output()

------------------------- Source Script Info -------------------------

Width     : 720
Height    : 576
Frames    : 72175
Time      : 48:07.000
Framerate : 25 (25/1)
Format    : YUV420P8

------------------------- Target Script Info -------------------------

Width     : 720
Height    : 576
Frames    : 72175
Time      : 48:07.000
Framerate : 25 (25/1)
Format    : YUV420P8

------------------------- Video encoding FFV1 -------------------------

ffmpeg N-111918-g0adaa90d89-x64-gcc13.2.0

C:\Portable\StaxRip-v2.29.0-x64\Apps\FrameServer\AviSynth\ffmpeg.exe -f vapoursynth -i "E:\video work\temp\Farscape 1x01 - Premiere_temp\Farscape 1x01 - Premiere RAW.vpy" -c:v ffv1 -aspect 1.36752 -an -y -hide_banner "E:\video work\temp\Farscape 1x01 - Premiere_temp\Farscape 1x01 - Premiere RAW_out.avi"

Input #0, vapoursynth, from 'E:\video work\temp\Farscape 1x01 - Premiere_temp\Farscape 1x01 - Premiere RAW.vpy':
  Duration: 00:48:07.00, start: 0.000000, bitrate: 0 kb/s
  Stream #0:0: Video: wrapped_avframe, yuv420p, 720x576, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (wrapped_avframe (native) -> ffv1 (native))
Press [q] to stop, [?] for help
Output #0, avi, to 'E:\video work\temp\Farscape 1x01 - Premiere_temp\Farscape 1x01 - Premiere RAW_out.avi':
  Metadata:
    ISFT            : Lavf60.11.100
  Stream #0:0: Video: ffv1 (FFV1 / 0x31564646), yuv420p(bt470bg/unknown/unknown, progressive), 720x576 [SAR 128:117 DAR 160:117], q=2-31, 200 kb/s, 25 fps, 25 tbn
    Metadata:
      encoder         : Lavc60.25.100 ffv1
[vapoursynth @ 000002693c4ea040] Error getting frame: 
Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2
[in#0/vapoursynth @ 000002693c4e9ec0] Error during demuxing: Generic error in an external library
[in#0/vapoursynth @ 000002693c4e9ec0] Error retrieving a packet from demuxer: Generic error in an external library
[out#0/avi @ 000002693c4eddc0] video:380236kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.017456%

Start:    15:45:55
End:      15:46:33
Duration: 00:00:37

General
Complete name         : E:\video work\temp\Farscape 1x01 - Premiere_temp\Farscape 1x01 - Premiere RAW_out.avi
Format                : AVI
Format/Info           : Audio Video Interleave
Format settings       : BitmapInfoHeader
File size             : 371 MiB
Duration              : 1 min 41 s
Overall bit rate mode : Variable
Overall bit rate      : 30.7 Mb/s
Frame rate            : 25.000 FPS
Writing application   : Lavf60.11.100

Video
ID                    : 0
Format                : FFV1
Format version        : Version 0
Codec ID              : FFV1
Duration              : 1 min 41 s
Bit rate mode         : Variable
Bit rate              : 30.7 Mb/s
Width                 : 720 pixels
Height                : 576 pixels
Display aspect ratio  : 4:3
Frame rate            : 25.000 FPS
Standard              : PAL
Color space           : YUV
Chroma subsampling    : 4:2:0
Bit depth             : 8 bits
Scan type             : Progressive
Compression mode      : Lossless
Bits/(Pixel*Frame)    : 2.957
Stream size           : 371 MiB (100%)
coder_type            : Golomb Rice

---------------------------- Muxing to MKV ----------------------------

mkvmerge 79.0

C:\Portable\StaxRip-v2.29.0-x64\Apps\Support\MKVToolNix\mkvmerge.exe -o "E:\video work\rips\farscape\Farscape 1x01 - Premiere\Farscape 1x01 - Premiere RAW.mkv" --no-audio --no-subs --no-chapters --no-attachments --no-track-tags --no-global-tags "E:\video work\temp\Farscape 1x01 - Premiere_temp\Farscape 1x01 - Premiere RAW_out.avi" --ui-language en

mkvmerge v79.0 ('Funeral Pyres') 64-bit
'E:\video work\temp\Farscape 1x01 - Premiere_temp\Farscape 1x01 - Premiere RAW_out.avi': Using the demultiplexer for the format 'AVI'.
'E:\video work\temp\Farscape 1x01 - Premiere_temp\Farscape 1x01 - Premiere RAW_out.avi' track 0: Using the output module for the format 'VfW compatible video'.
The file 'E:\video work\rips\farscape\Farscape 1x01 - Premiere\Farscape 1x01 - Premiere RAW.mkv' has been opened for writing.
The cue entries (the index) are being written...
Multiplexing took 1 second.

Start:    15:46:33
End:      15:46:35
Duration: 00:00:01

----------------------- Media Info Target File -----------------------

General
Complete name         : E:\video work\rips\farscape\Farscape 1x01 - Premiere\Farscape 1x01 - Premiere RAW.mkv
Format                : Matroska
Format version        : Version 4
File size             : 371 MiB
Duration              : 1 min 41 s
Overall bit rate mode : Variable
Overall bit rate      : 30.7 Mb/s
Frame rate            : 25.000 FPS
Encoded date          : 2023-11-01 15:46:33 UTC
Writing application   : mkvmerge v79.0 ('Funeral Pyres') 64-bit
Writing library       : libebml v1.4.4 + libmatroska v1.7.1

Video
ID                    : 1
Format                : FFV1
Format version        : Version 0
Codec ID              : V_MS/VFW/FOURCC / FFV1
Duration              : 1 min 41 s
Bit rate mode         : Variable
Bit rate              : 30.7 Mb/s
Width                 : 720 pixels
Height                : 576 pixels
Display aspect ratio  : 4:3
Frame rate mode       : Constant
Frame rate            : 25.000 FPS
Standard              : PAL
Color space           : YUV
Chroma subsampling    : 4:2:0
Bit depth             : 8 bits
Compression mode      : Lossless
Bits/(Pixel*Frame)    : 2.957
Stream size           : 371 MiB (100%)
Default               : Yes
Forced                : No
coder_type            : Golomb Rice

---------------------------- Job Complete ----------------------------

Start:    15:45:52
End:      15:46:35
Duration: 00:00:42

--------------------------- Frame Mismatch ---------------------------

WARNING: Target file has 2540 frames, but should have 72175 frames!
Encoding was terminated at 3.5%!

```

**Comment by Statick** [comment]
update, what's been confusing me is that changing the variables "firstnum" and "lastnum" for hard coded values seemed to change the behaviour

in fact, it was the value I was reading from the file that was the problem, and changing that value by hard coding it fixes the problem - and if I hard code the same value as I was using in the overrides file, then it again crashes the encoder

```
                # this crashes the encoder on frame 2588
                if n >= 2588:
                    output = clip
                    message = "debug"
                    break
```

```
                # this works fine without crashing
                if n >= 2500:
                    output = clip
                    message = "debug"
                    break
```

**Comment by Statick** [comment]
it seems that if I use values above 2540 for the test "if n>= 2540:" then the encoder crashes on that frame number
if I use values less than or equal to 2540 then the encoder does not crash

**Comment by Statick** [comment]
after testing the output script in vspipe and vs editor I get the same problems there - vspipe crashes but vs edit does not. so it looks like this is nothing to do with staxrip at all. I notice in vs edit that the console output is flooded with warnings about a cache, which are being generated by the tdeintmod plugin, the warnings and the crash go away if I remove that plugin so I suspect the problem is to do with this happening within frameeval
