### ISSUE TITLE
UI crash for Stax 2.30.0

### ISSUE THREAD

**Issue by mshedsilegx** [staxrip/staxrip#1158]
**Describe the bug**
UI crashes immediately with fatal exception in 2.30.0, all is fine in 2.29.0

**Expected behavior**
No crash, and UI displays

**Logs**
```
Application: StaxRip.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at StaxRip.Vulkan.vkEnumerateInstanceVersion(UInt32 ByRef)
   at StaxRip.Vulkan.get_IsSupported()
   at StaxRip.Project..ctor()
   at StaxRip.GlobalClass..ctor()
   at StaxRip.ShortcutModule..cctor()

Exception Info: System.TypeInitializationException
   at StaxRip.Startup.Main()
```

```
Faulting application name: StaxRip.exe, version: 2.30.0.0, time stamp: 0x657e1e1f
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3758, time stamp: 0xd80f8f12
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0x25bc
Faulting application start time: 0x01da31f2e80622b2
Faulting application path: D:\apps\mmedia\dvdtools\staxrip\StaxRip.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 7baa5c2d-5686-43b9-9960-dd82c092889c
Faulting package full name: 
Faulting package-relative application ID: 
```

OS: Windows 10 22H2 (OS Build 19045.3803)
DotNet desktop: 
```
Host:
  Version:      7.0.14
  Architecture: x64
  Commit:       808851b07a

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by nero-0** [comment]
Same here (I guess).
StaxRip simply closes unexpectedly after opening, without showing any message error in v2.30.0, v2.29.0 is just fine.

**Comment by Dendraspis** [comment]
Did/Do you use clean settings or one from a previous version?

**Comment by mshedsilegx** [comment]
Clean settings for me

**Comment by mshedsilegx** [comment]
![image](https://github.com/staxrip/staxrip/assets/32753787/d11c7d12-da33-427c-8ed0-a523fcab10bc)

This is what I see immediately after opening StaxRip.exe

**Comment by Dendraspis** [comment]
Please replace the `StaxRip.exe` file with this one and check again, if the issue is gone:
[StaxRip v2.30.1.zip](https://github.com/staxrip/staxrip/files/13709377/StaxRip.v2.30.1.zip)

**Comment by mshedsilegx** [comment]
Yes, confirmed working for me now. Thanks !

**Comment by nero-0** [comment]
Working for me too, looks like you found what was wrong. Thanks for looking into this so quickly, Dendraspis. :)

**Comment by Dendraspis** [comment]
Thanks for your feedbacks. It also helped to see the log.  👍
 Glad I could fix it so fast. So just use this version till the next release.
