### ISSUE TITLE
Error showing length cannot be zero while importing some files

### ISSUE THREAD

**Issue by Dendraspis** [staxrip/staxrip#1168]
### Discussed in https://github.com/staxrip/staxrip/discussions/1165

<div type='discussions-op-text'>

<sup>Originally posted by **rahatbracu** December 26, 2023</sup>
![image](https://github.com/staxrip/staxrip/assets/146360339/3469f301-daf0-495b-920c-c1e8bf00d4da)
</div>

**Comment by Dendraspis** [comment]
@rahatbracu 
I need definitely more info on that. The log file or at least the whole error message after you've clicked on `Show Details` and the Media Info of the source file(s).

**Comment by rahatbracu** [comment]
> @rahatbracu I need definitely more info on that. The log file or at least the whole error message after you've clicked on `Show Details` and the Media Info of the source file(s).



ArgumentOutOfRangeException (v2.30.0)

Length cannot be less than zero.
Parameter name: length

System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at StaxRip.StringExtensions.Shorten(String value, Int32 maxLength) in D:\Code\Github\staxrip\staxrip\Source\General\Extensions.vb:line 646
   at StaxRip.Audio.GetBaseNameForStream(String filePath, AudioStream stream) in D:\Code\Github\staxrip\staxrip\Source\General\Audio.vb:line 92
   at StaxRip.mkvDemuxer.Demux(String sourcefile, IEnumerable`1 audioStreams, IEnumerable`1 subtitles, AudioProfile ap, Project proj, Boolean onlyEnabled, Boolean videoDemuxing, Boolean overrideExisting, String title, Boolean useStreamName) in D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:line 949
   at StaxRip.mkvDemuxer.Run(Project proj) in D:\Code\Github\staxrip\staxrip\Source\General\Demux.vb:line 765
   at StaxRip.MainForm.Demux() in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 3422
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2218 @Dendraspis

**Comment by Dendraspis** [comment]
Will be fixed in the next release...
