### ISSUE TITLE
Audio isn't MPEG-2/4 AAC with ADTS , BitStream Not Compliant errors

### ISSUE THREAD

**Issue by dhry** [staxrip/staxrip#12]
Have been getting this a lot lately across multiple different h264 MKVs to be recompressed. Is there something I can do to identify what the problem is being reported below, or a way to have the muxer be less strict somehow? Or is there a different muxer that can be used?

-------------------- Demux MKV using mkvextract 34 --------------------

"C:\Program Files\StaxRip\Apps\Support\MKVToolNix\mkvextract.exe" K:\TBD\wop1.mkv tracks 2:"K:\TBD\wop1_temp\wop1 ID3 English" 1:"K:\TBD\wop1_temp\wop1 ID1 English.aac" --ui-language en

Extracting track 1 with the CodecID 'A_AAC' to the file 'K:\TBD\wop1_temp\wop1 ID1 English.aac'. Container format: raw AAC file with ADTS headers
Error: Extraction of track ID 2 with the CodecID 'S_DVBSUB' is not supported.

Start:    8:22:35 AM
End:      8:22:36 AM
Duration: 00:00:00

General
Complete name : K:\TBD\wop1_temp\wop1 ID1 English.aac
File size     : 0.00 Byte

--------- Error Mux AAC to M4A using MP4Box 0.7.2-DEV-rev1009 ---------

Mux AAC to M4A using MP4Box 0.7.2-DEV-rev1009 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

------------ Mux AAC to M4A using MP4Box 0.7.2-DEV-rev1009 ------------

"C:\Program Files\StaxRip\Apps\Support\MP4Box\MP4Box.exe" -add "K:\TBD\wop1_temp\wop1 ID1 English.aac:name= " -new "K:\TBD\wop1_temp\wop1 ID1 English.m4a"

[33mAudio isn't MPEG-2/4 AAC with ADTS
[0mError importing K:\TBD\wop1_temp\wop1 ID1 English.aac:name= : BitStream Not Compliant

------------ Mux AAC to M4A using MP4Box 0.7.2-DEV-rev1009 ------------

"C:\Program Files\StaxRip\Apps\Support\MP4Box\MP4Box.exe" -add "K:\TBD\wop1_temp\wop1 ID1 English.aac:name= " -new "K:\TBD\wop1_temp\wop1 ID1 English.m4a"

[33mAudio isn't MPEG-2/4 AAC with ADTS
[0mError importing K:\TBD\wop1_temp\wop1 ID1 English.aac:name= : BitStream Not Compliant

Start:    8:22:36 AM
End:      8:22:36 AM
Duration: 00:00:00

------------------------------ Exception ------------------------------

StaxRip.ErrorAbortException: Mux AAC to M4A using MP4Box 0.7.2-DEV-rev1009 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

------------ Mux AAC to M4A using MP4Box 0.7.2-DEV-rev1009 ------------

"C:\Program Files\StaxRip\Apps\Support\MP4Box\MP4Box.exe" -add "K:\TBD\wop1_temp\wop1 ID1 English.aac:name= " -new "K:\TBD\wop1_temp\wop1 ID1 English.m4a"

[33mAudio isn't MPEG-2/4 AAC with ADTS
[0mError importing K:\TBD\wop1_temp\wop1 ID1 English.aac:name= : BitStream Not Compliant

   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 339
   at StaxRip.mkvDemuxer.Demux(String sourcefile, IEnumerable`1 audioStreams, IEnumerable`1 subtitles, AudioProfile ap, Project proj, Boolean onlyEnabled, Boolean videoDemuxing) in D:\Projekte\VB\staxrip\General\Demux.vb:line 808
   at StaxRip.mkvDemuxer.Run(Project proj) in D:\Projekte\VB\staxrip\General\Demux.vb:line 662
   at StaxRip.MainForm.Demux() in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 3102
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Projekte\VB\staxrip\Forms\MainForm.vb:line 1973

**Comment by dhry** [comment]
MediaInfo shows the following about the audio, if it helps
---
Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 58 min 3 s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No

**Comment by dhry** [comment]
I think I know what the problem is.
This DVBSUB item in the file jams up mp4box for some reason.
I stripped it from the mkv using mkvtoolnix and now the file transcodes perfectly.
![image](https://user-images.githubusercontent.com/4991066/60146601-08746f80-977f-11e9-8c98-a480f5a88071.png)
