### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1208]
SerializationException (v2.34.0)

Type 'System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[StaxRip.DolbyVisionMetadataFile, StaxRip, Version=2.34.0.0, Culture=neutral, PublicKeyToken=null]]' in Assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.

System.Runtime.Serialization.SerializationException: Type 'System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[StaxRip.DolbyVisionMetadataFile, StaxRip, Version=2.34.0.0, Culture=neutral, PublicKeyToken=null]]' in Assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at StaxRip.SafeSerialization.GetObjectData(Object o) in D:\Code\Github\staxrip\staxrip\Source\General\General.vb:line 367
   at StaxRip.SafeSerialization.Serialize(Object o, String path) in D:\Code\Github\staxrip\staxrip\Source\General\General.vb:line 282
   at StaxRip.MainForm.SaveProjectPath(String path) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 4203

**Comment by Dendraspis** [comment]
Head over to https://github.com/staxrip/staxrip/issues/1201#issuecomment-1912275919

The hotfix, for all who were the first to download `v2.34.0`, is also available on the release page:
https://github.com/staxrip/staxrip/releases/tag/v2.34.0
