### ISSUE TITLE
IVTC for Vapoursynth is broken

### ISSUE THREAD

**Issue by shodan5000** [staxrip/staxrip#1209]
Trying to use IVTC Vapoursynth filter produces this error code:

Script Error

Python exception: No attribute with the name vivtc exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
  File "src\\cython\\vapoursynth.pyx", line 3124, in vapoursynth._vpy_evaluate
  File "src\\cython\\vapoursynth.pyx", line 3125, in vapoursynth._vpy_evaluate
  File "D:\StaxRip_temp\Tales from the Crypt - S01E02 - And All Through the House_temp\Tales from the Crypt - S01E02 - And All Through the House_new.vpy", line 12, in <module>
    clip = core.vivtc.VFM(clip, 1)
           ^^^^^^^^^^
  File "src\\cython\\vapoursynth.pyx", line 2639, in vapoursynth._CoreProxy.__getattr__
  File "src\\cython\\vapoursynth.pyx", line 2494, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name vivtc exists. Did you mistype a plugin namespace?

**Comment by shodan5000** [comment]
Of Staxrip? Observed on 2.33 and 2.34.
