### ISSUE TITLE
Error Extract Dolby Vision metadata - caused by DELAY in a file name!

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#1219]
Error Extract Dolby Vision metadata (v2.35.0)

Extract Dolby Vision metadata returned exit code: 1 (0x1)

I get this error on an SDR file

movie.mkv
movie.DELAY 10ms.ac3

Just because I have a delay in the separate audio file name I get this Dolby Vision error! Again the movie is SDR.
if I rename the movie.DELAY 10ms.ac3 to movie.ac3, then I get no error! So strange.

```
-------------------- Extract Dolby Vision metadata --------------------

DoVi_Tool 2.1.0

"Z:\Video\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe" -hide_banner -probesize 20M -i "X:\New Folder\movie.DELAY 10ms.ac3" -an -sn -dn -c:v copy -bsf:v hevc_mp4toannexb -f hevc - | "Z:\Video\StaxRip\Apps\Support\DoVi_Tool\dovi_tool.exe" -m 2 extract-rpu - -o "X:\New Folder\movie_temp\HDRDVmetadata.rpu"

[eac3 @ 0000023dac139a40] Estimating duration from bitrate, this may be inaccurate
Input #0, eac3, from 'X:\New Folder\movie.DELAY 10ms.ac3':
  Duration: 01:54:00.99, start: 0.000000, bitrate: 384 kb/s
  Stream #0:0: Audio: eac3, 48000 Hz, 5.1(side), fltp, 384 kb/s
Output #0, hevc, to 'pipe:':
[out#0/hevc @ 0000023dac0466c0] Output file does not contain any stream
Error opening output file -.
Error opening output files: Invalid argument
Error: No frames parsed!

StaxRip.ErrorAbortException: Extract Dolby Vision metadata returned exit code: 1 (0x1)


-------------------- Extract Dolby Vision metadata --------------------

DoVi_Tool 2.1.0

"Z:\Video\StaxRip\Apps\FrameServer\AviSynth\ffmpeg.exe" -hide_banner -probesize 20M -i "X:\New Folder\movie.DELAY 10ms.ac3" -an -sn -dn -c:v copy -bsf:v hevc_mp4toannexb -f hevc - | "Z:\Video\StaxRip\Apps\Support\DoVi_Tool\dovi_tool.exe" -m 2 extract-rpu - -o "X:\New Folder\movie_temp\HDRDVmetadata.rpu"

[eac3 @ 0000023dac139a40] Estimating duration from bitrate, this may be inaccurate
Input #0, eac3, from 'X:\New Folder\movie.DELAY 10ms.ac3':
  Duration: 01:54:00.99, start: 0.000000, bitrate: 384 kb/s
  Stream #0:0: Audio: eac3, 48000 Hz, 5.1(side), fltp, 384 kb/s
Output #0, hevc, to 'pipe:':
[out#0/hevc @ 0000023dac0466c0] Output file does not contain any stream
Error opening output file -.
Error opening output files: Invalid argument
Error: No frames parsed!


   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 353
   at StaxRip.MainForm.ExtractDolbyVisionMetadata(Project proj) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 3581
```

**Comment by Dendraspis** [comment]
Thanks for the report.
I have already fixed it for the next release, so that this can't happen again.

**Comment by IevgenSobko** [comment]
I had the same issue because the original remux contained `,` symbol in its name.
After removing it DV metadata extracted successfully.

**Comment by Dendraspis** [comment]
The next release will take a while, but I made this hotfix, that restricts the finding of metadata a bit more. It is compatible with `v2.35`, so you can keep your settings:
[StaxRip_v2.35.8.zip](https://github.com/staxrip/staxrip/files/14221503/StaxRip_v2.35.8.zip)

@IevgenSobko 
Can you please also check this hotfix out to see, if it solves your issues (in case it happens from time to time)?
If not, please open a new issue because then it must be something completely different.

**Comment by Zodler** [comment]
Fixed. Thank you.

**Comment by IevgenSobko** [comment]
@Dendraspis checked and opened new issue #1238
