### ISSUE TITLE
Error Extract Level5 data from RPU metadata file

### ISSUE THREAD

**Issue by IevgenSobko** [staxrip/staxrip#1238]
**Describe the bug**
Getting following error when trying to extract DV RPU.
The issue seems is related to `,` symbol in filename because if I rename original file to not contain it extraction works OK.
```
Error Extract Level5 data from RPU metadata file (v2.35.8)

Extract Level5 data from RPU metadata file returned exit code: 2 (0x2)


------------- Extract Level5 data from RPU metadata file -------------

DoVi_Tool 2.1.0

D:\StaxRip-v2.35.0-x64\Apps\Support\DoVi_Tool\dovi_tool.exe export --data "level5=K:\Indiana Jones and the Last Crusade (1989) UHD BDRemux 2160p Dolby Vision, HDR_temp\HDRDVmetadata_L5.json" -i "K:\Indiana Jones and the Last Crusade (1989) UHD BDRemux 2160p Dolby Vision, HDR_temp\HDRDVmetadata.rpu"

error: invalid value ' HDR_temp\HDRDVmetadata_L5.json' for '--data <data>'
  [possible values: all, scenes, level5]
For more information, try '--help'.

StaxRip.ErrorAbortException: Extract Level5 data from RPU metadata file returned exit code: 2 (0x2)


------------- Extract Level5 data from RPU metadata file -------------

DoVi_Tool 2.1.0

D:\StaxRip-v2.35.0-x64\Apps\Support\DoVi_Tool\dovi_tool.exe export --data "level5=K:\Indiana Jones and the Last Crusade (1989) UHD BDRemux 2160p Dolby Vision, HDR_temp\HDRDVmetadata_L5.json" -i "K:\Indiana Jones and the Last Crusade (1989) UHD BDRemux 2160p Dolby Vision, HDR_temp\HDRDVmetadata.rpu"

error: invalid value ' HDR_temp\HDRDVmetadata_L5.json' for '--data <data>'
  [possible values: all, scenes, level5]
For more information, try '--help'.


   at StaxRip.Proc.Start()
   at StaxRip.DolbyVisionMetadataFile.WriteLevel5Export(Boolean overwrite)
```

**Comment by Dendraspis** [comment]
1. No need to ping me
2. That is a `dovi_tool` issue. I have opened an issue for that, we will see....

**Comment by Dendraspis** [comment]
Great, the issue was already closed. The solution is to avoid commas.

I will see what I can do....

**Comment by Dendraspis** [comment]
I have implemented a workaround, should be fine with the next version...
