### ISSUE TITLE
Always crop throws an exception error

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#1276]
Hi,

Just tried it on the last version (v2.37). Clean install too.
If you set auto crop after opening to "always" it will throw an error as following:

"TargetInvocationException (v2.37.0)

Exception has been thrown by the target of an invocation.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at StaxRip.GlobalClass.RunAutoCrop(Action`1 progressAction) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 1431
   at StaxRip.MainForm.StartAutoCrop() in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 6022
   at StaxRip.MainForm.ShowOptionsDialog(String pagePath) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 5473
   at StaxRip.MainForm.ShowOptionsDialog() in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 4680
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at StaxRip.CommandManager.Process(Command command, List`1 params) in D:\Code\Github\staxrip\staxrip\Source\General\General.vb:line 1098"

**Comment by Dendraspis** [comment]
Fix is available here:  https://github.com/staxrip/staxrip/releases/tag/v2.37.1
You just need to download and replace the exe file.

Thanks for the report, haven't encountered that issue in my tests.  😖
