### ISSUE TITLE
When starting up another staxrip to run 2 at once i get error.

### ISSUE THREAD

**Issue by chowderhead** [staxrip/staxrip#1288]
IOException (v2.36.0)

The process cannot access the file 'F:\Downloads\APPS and INSTALLERS\StaxRip-v2.36.0-x64\Debug.log' because it is being used by another process.

System.IO.IOException: The process cannot access the file 'F:\Downloads\APPS and INSTALLERS\StaxRip-v2.36.0-x64\Debug.log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at StaxRip.MainForm..ctor() in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 1069
   at StaxRip.Startup.Main() in D:\Code\Github\staxrip\staxrip\Source\General\Misc.vb:line 999

stopping all rips and quitting all staxrip wait 10 seconds (MUST wait) then launch 3 episodes and they all run fine.

**Comment by Dendraspis** [comment]
To prevent that you have to disable `Enable debug logging` in the Settings, which also should just be used when needed.
