### ISSUE TITLE
Error: Illegal characters in path

### ISSUE THREAD

**Issue by johnvick** [staxrip/staxrip#1339]
I don't want to waste your time until I have investigated this further at my end.

2.38 works fine on Ryzen desktop, 2.38.* produce errors similar to my last post here.

2.38.7 works fine on Intel laptop.

Question is how do I ensure all traces of Staxrip are removed to ensure a fresh start?

I have removed all the paths suggested for settings folder on startup. Could there be registry entries? I have been using Staxrip for maybe 4+ years on same desktop.

**Comment by johnvick** [comment]
Clean install as your suggestions to - C:\StaxRip-v2.38.7-x64

Add video file - no settings changed - error log:

`ArgumentException (v2.38.7)

Illegal characters in path.

System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at StaxRip.Package.FindInPathEnvVar(String filename) in D:\Code\Github\staxrip\staxrip\Source\General\Package.vb:line 3221
   at StaxRip.Package.FindEverywhere(String fileName, String ignorePath) in D:\Code\Github\staxrip\staxrip\Source\General\Package.vb:line 3168
   at StaxRip.Package.get_Path() in D:\Code\Github\staxrip\staxrip\Source\General\Package.vb:line 3114
   at StaxRip.AppsForm.SearchTextBox_TextChanged() in D:\Code\Github\staxrip\staxrip\Source\Forms\AppsForm.vb:line 689
   at StaxRip.AppsForm..ctor() in D:\Code\Github\staxrip\staxrip\Source\Forms\AppsForm.vb:line 412
   at StaxRip.Package.VerifyOK(Boolean showEvenIfNotRequired) in D:\Code\Github\staxrip\staxrip\Source\General\Package.vb:line 2793
   at StaxRip.GlobalClass.VerifyRequirements() in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 564
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Code\Github\staxrip\staxrip\Source\Forms\MainForm.vb:line 2109

`
I tried this with several video files, same error. Same with NVENC and software 264/265 encoders.

**Comment by Dendraspis** [comment]
Okay, this is related to a change in `v2.38.1`, so `v2.38.0` should not be affected.

What did you do to get this error message?

**Comment by johnvick** [comment]
All I did was open a video file:

`C:\Users\johnv>echo %PATH%
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH";C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\WireGuard\;C:\Program Files\NVIDIA Corporation\NVIDIA App\NvDLISR;C:\Program Files\NVIDIA Corporation\NVIDIA App\NvDLISR;C:\Program Files\NVIDIA Corporation\NVIDIA App\NvDLISR;C:\Program Files\PowerShell\7\;C:\Program Files\Tailscale\;C:\Users\johnv\AppData\Local\Microsoft\WindowsApps;`

**Comment by Dendraspis** [comment]
Your Path variable contains a path that has an invalid character:
`C:\WINDOWS\System32\OpenSSH"`

I guess after you remove that ending `"` StaxRip will work without issues.

**Comment by johnvick** [comment]
That fixed it - thanks very much. What an obscure error (from where I sit anyway).

**Comment by Dendraspis** [comment]
Thank you very much, too.  ❤️ 

Glad this fixed your problem.
