### ISSUE TITLE
Getting error if use these two filters together

### ISSUE THREAD

**Issue by darkcity87** [staxrip/staxrip#1340]
**Describe the bug**
I am getting error message if i use smdegrain + edgeclener or mctemporaldenoise + edgeclener. There is no error if i use only one of these filters. Also preview work fine no error.

I used same filter chain many times before not sure which version broke.

**Expected behavior**
no error

**How to reproduce the issue**

smdegrain + edgeclener

```
  1: import os, sys
  2: import vapoursynth as vs
  3: core = vs.core
  4: 
  5: sys.path.append(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Scripts")
  6: import importlib.machinery
  7: havsfunc = importlib.machinery.SourceFileLoader('havsfunc', r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Scripts\havsfunc.py").load_module()
  8: mvsfunc = importlib.machinery.SourceFileLoader('mvsfunc', r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\mvsfunc\mvsfunc.py").load_module()
  9: adjust = importlib.machinery.SourceFileLoader('adjust', r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Scripts\adjust.py").load_module()
 10: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\Dual\ffms2\ffms2.dll", altsearchpath=True)
 11: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\fmtconv\fmtconv.dll", altsearchpath=True)
 12: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\AddGrain\AddGrain.dll", altsearchpath=True)
 13: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\AWarpSharp2\libawarpsharp2.dll", altsearchpath=True)
 14: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\CAS\CAS.dll", altsearchpath=True)
 15: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\CTMF\CTMF.dll", altsearchpath=True)
 16: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\DCTFilter\DCTFilter.dll", altsearchpath=True)
 17: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Deblock\Deblock.dll", altsearchpath=True)
 18: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\DFTTest\DFTTest.dll", altsearchpath=True)
 19: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\EEDI2\EEDI2.dll", altsearchpath=True)
 20: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\EEDI3m\EEDI3m.dll", altsearchpath=True)
 21: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\FFT3DFilter\fft3dfilter.dll", altsearchpath=True)
 22: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\Dual\flash3kyuu_deband\flash3kyuu_deband.dll", altsearchpath=True)
 23: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\FluxSmooth\libfluxsmooth.dll", altsearchpath=True)
 24: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\HQDN3D\libhqdn3d.dll", altsearchpath=True)
 25: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\Dual\KNLMeansCL\KNLMeansCL.dll", altsearchpath=True)
 26: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\MiscFilters\MiscFilters.dll", altsearchpath=True)
 27: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\BM3D\BM3D.dll", altsearchpath=True)
 28: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\mvtools\libmvtools.dll", altsearchpath=True)
 29: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\nnedi3\libnnedi3.dll", altsearchpath=True)
 30: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\nnedi3\NNEDI3CL.dll", altsearchpath=True)
 31: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\RemoveGrainVS\RemoveGrainVS.dll", altsearchpath=True)
 32: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Sangnom\libsangnom.dll", altsearchpath=True)
 33: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\SVPFlow\svpflow1_vs64.dll", altsearchpath=True)
 34: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\SVPFlow\svpflow2_vs64.dll", altsearchpath=True)
 35: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\TTempSmooth\TTempSmooth.dll", altsearchpath=True)
 36: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\nnedi3\vsznedi3.dll", altsearchpath=True)
 37: 
 38: tcFile = r"D:\t\a\test\video_temp\video_timestamps.txt" # timestamps file path
 39: clip = core.ffms2.Source(r"D:\t\a\test\video.mkv", cachefile=r"D:\t\a\test\video_temp\temp.ffindex", timecodes=tcFile) if os.path.exists(tcFile) else core.ffms2.Source(r"D:\t\a\test\video.mkv", cachefile=r"D:\t\a\test\video_temp\temp.ffindex")
 40: core.max_cache_size = 12288
 41: clip = core.fmtc.bitdepth(clip, bits=16)
 42: clip = havsfunc.SMDegrain(clip, tr=2, thSAD=300, RefineMotion=True)
 43: clip = havsfunc.EdgeCleaner(clip)
 44: 
 45: clip.set_output()

```

```
Error Video encoding (v2.38.7)

NVEncC 7.50

C:\Portable\StaxRip-v2.38.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe --avsdll C:\Portable\StaxRip-v2.38.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll --cqp 65:82:90 --codec av1 --preset P7 --output-depth 10 --aq --aq-strength 14 --ref 4 --lookahead 32 --colormatrix bt709 --colorprim bt709 --transfer bt709 --mv-precision q-pel -i D:\t\a\test\video_temp\video_new.vpy -o D:\t\a\test\video_temp\video_new_out.av1

--------------------------------------------------------------------------------
D:\t\a\test\video_temp\video_new_out.av1
--------------------------------------------------------------------------------
vpy: VapourSynth script error.
vpy: Python exception: No module named 'mvsfunc'
vpy: Traceback (most recent call last):
vpy:   File "src\\cython\\vapoursynth.pyx", line 3233, in vapoursynth._vpy_evaluate
vpy:   File "src\\cython\\vapoursynth.pyx", line 3234, in vapoursynth._vpy_evaluate
vpy:   File "<undefined>", line 7, in <module>
vpy:   File "<frozen importlib._bootstrap_external>", line 649, in _check_name_wrapper
vpy:   File "<frozen importlib._bootstrap_external>", line 1176, in load_module
vpy:   File "<frozen importlib._bootstrap_external>", line 1000, in load_module
vpy:   File "<frozen importlib._bootstrap>", line 537, in _load_module_shim
vpy:   File "<frozen importlib._bootstrap>", line 966, in _load
vpy:   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
vpy:   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
vpy:   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
vpy:   File "C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Scripts\havsfunc.py", line 6, in <module>
vpy:     import mvsfunc as mvf
vpy: ModuleNotFoundError: No module named 'mvsfunc'
failed to initialize file reader(s).
Failed to open input file.


Video encoding returned exit code: 1 (0x1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

StaxRip.ErrorAbortException: NVEncC 7.50

C:\Portable\StaxRip-v2.38.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe --avsdll C:\Portable\StaxRip-v2.38.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll --cqp 65:82:90 --codec av1 --preset P7 --output-depth 10 --aq --aq-strength 14 --ref 4 --lookahead 32 --colormatrix bt709 --colorprim bt709 --transfer bt709 --mv-precision q-pel -i D:\t\a\test\video_temp\video_new.vpy -o D:\t\a\test\video_temp\video_new_out.av1

--------------------------------------------------------------------------------
D:\t\a\test\video_temp\video_new_out.av1
--------------------------------------------------------------------------------
vpy: VapourSynth script error.
vpy: Python exception: No module named 'mvsfunc'
vpy: Traceback (most recent call last):
vpy:   File "src\\cython\\vapoursynth.pyx", line 3233, in vapoursynth._vpy_evaluate
vpy:   File "src\\cython\\vapoursynth.pyx", line 3234, in vapoursynth._vpy_evaluate
vpy:   File "<undefined>", line 7, in <module>
vpy:   File "<frozen importlib._bootstrap_external>", line 649, in _check_name_wrapper
vpy:   File "<frozen importlib._bootstrap_external>", line 1176, in load_module
vpy:   File "<frozen importlib._bootstrap_external>", line 1000, in load_module
vpy:   File "<frozen importlib._bootstrap>", line 537, in _load_module_shim
vpy:   File "<frozen importlib._bootstrap>", line 966, in _load
vpy:   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
vpy:   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
vpy:   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
vpy:   File "C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Scripts\havsfunc.py", line 6, in <module>
vpy:     import mvsfunc as mvf
vpy: ModuleNotFoundError: No module named 'mvsfunc'
failed to initialize file reader(s).
Failed to open input file.


Video encoding returned exit code: 1 (0x1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


   konum: StaxRip.Proc.Start() D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb içinde: satır 366
   konum: StaxRip.NVEnc.Encode() D:\Code\Github\staxrip\staxrip\Source\Encoding\NVEnc.vb içinde: satır 141
   konum: StaxRip.GlobalClass._Closure$__._Lambda$__126-8() D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb içinde: satır 367
   konum: System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   konum: StaxRip.GlobalClass.ProcessJob(String jobPath) D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb içinde: satır 376
```

mctemporaldenoise + edgeclener

```
  1: import os, sys
  2: import vapoursynth as vs
  3: core = vs.core
  4: 
  5: sys.path.append(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Scripts")
  6: import importlib.machinery
  7: havsfunc = importlib.machinery.SourceFileLoader('havsfunc', r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Scripts\havsfunc.py").load_module()
  8: mvsfunc = importlib.machinery.SourceFileLoader('mvsfunc', r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\mvsfunc\mvsfunc.py").load_module()
  9: adjust = importlib.machinery.SourceFileLoader('adjust', r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Scripts\adjust.py").load_module()
 10: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\Dual\ffms2\ffms2.dll", altsearchpath=True)
 11: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\fmtconv\fmtconv.dll", altsearchpath=True)
 12: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\AddGrain\AddGrain.dll", altsearchpath=True)
 13: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\AWarpSharp2\libawarpsharp2.dll", altsearchpath=True)
 14: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\CAS\CAS.dll", altsearchpath=True)
 15: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\CTMF\CTMF.dll", altsearchpath=True)
 16: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\DCTFilter\DCTFilter.dll", altsearchpath=True)
 17: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Deblock\Deblock.dll", altsearchpath=True)
 18: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\DFTTest\DFTTest.dll", altsearchpath=True)
 19: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\EEDI2\EEDI2.dll", altsearchpath=True)
 20: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\EEDI3m\EEDI3m.dll", altsearchpath=True)
 21: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\FFT3DFilter\fft3dfilter.dll", altsearchpath=True)
 22: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\Dual\flash3kyuu_deband\flash3kyuu_deband.dll", altsearchpath=True)
 23: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\FluxSmooth\libfluxsmooth.dll", altsearchpath=True)
 24: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\HQDN3D\libhqdn3d.dll", altsearchpath=True)
 25: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\Dual\KNLMeansCL\KNLMeansCL.dll", altsearchpath=True)
 26: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\MiscFilters\MiscFilters.dll", altsearchpath=True)
 27: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\BM3D\BM3D.dll", altsearchpath=True)
 28: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\mvtools\libmvtools.dll", altsearchpath=True)
 29: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\nnedi3\libnnedi3.dll", altsearchpath=True)
 30: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\nnedi3\NNEDI3CL.dll", altsearchpath=True)
 31: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\RemoveGrainVS\RemoveGrainVS.dll", altsearchpath=True)
 32: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Sangnom\libsangnom.dll", altsearchpath=True)
 33: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\SVPFlow\svpflow1_vs64.dll", altsearchpath=True)
 34: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\SVPFlow\svpflow2_vs64.dll", altsearchpath=True)
 35: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\TTempSmooth\TTempSmooth.dll", altsearchpath=True)
 36: core.std.LoadPlugin(r"C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\nnedi3\vsznedi3.dll", altsearchpath=True)
 37: 
 38: tcFile = r"D:\t\a\test\video_temp\video_timestamps.txt" # timestamps file path
 39: clip = core.ffms2.Source(r"D:\t\a\test\video.mkv", cachefile=r"D:\t\a\test\video_temp\temp.ffindex", timecodes=tcFile) if os.path.exists(tcFile) else core.ffms2.Source(r"D:\t\a\test\video.mkv", cachefile=r"D:\t\a\test\video_temp\temp.ffindex")
 40: core.max_cache_size = 12288
 41: clip = core.fmtc.bitdepth(clip, bits=16)
 42: clip = havsfunc.MCTemporalDenoise(i=clip, settings='medium')
 43: clip = havsfunc.EdgeCleaner(clip)
 44: 
 45: clip.set_output()

```
```

Error Video encoding (v2.38.7)

NVEncC 7.50

C:\Portable\StaxRip-v2.38.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe --avsdll C:\Portable\StaxRip-v2.38.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll --cqp 65:82:90 --codec av1 --preset P7 --output-depth 10 --aq --aq-strength 14 --ref 4 --lookahead 32 --colormatrix bt709 --colorprim bt709 --transfer bt709 --mv-precision q-pel -i D:\t\a\test\video_temp\video_new.vpy -o D:\t\a\test\video_temp\video_new_out.av1

--------------------------------------------------------------------------------
D:\t\a\test\video_temp\video_new_out.av1
--------------------------------------------------------------------------------
vpy: VapourSynth script error.
vpy: Python exception: No module named 'mvsfunc'
vpy: Traceback (most recent call last):
vpy:   File "src\\cython\\vapoursynth.pyx", line 3233, in vapoursynth._vpy_evaluate
vpy:   File "src\\cython\\vapoursynth.pyx", line 3234, in vapoursynth._vpy_evaluate
vpy:   File "<undefined>", line 7, in <module>
vpy:   File "<frozen importlib._bootstrap_external>", line 649, in _check_name_wrapper
vpy:   File "<frozen importlib._bootstrap_external>", line 1176, in load_module
vpy:   File "<frozen importlib._bootstrap_external>", line 1000, in load_module
vpy:   File "<frozen importlib._bootstrap>", line 537, in _load_module_shim
vpy:   File "<frozen importlib._bootstrap>", line 966, in _load
vpy:   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
vpy:   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
vpy:   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
vpy:   File "C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Scripts\havsfunc.py", line 6, in <module>
vpy:     import mvsfunc as mvf
vpy: ModuleNotFoundError: No module named 'mvsfunc'
failed to initialize file reader(s).
Failed to open input file.


Video encoding returned exit code: 1 (0x1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

StaxRip.ErrorAbortException: NVEncC 7.50

C:\Portable\StaxRip-v2.38.0-x64\Apps\Encoders\NVEncC\NVEncC64.exe --avsdll C:\Portable\StaxRip-v2.38.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll --cqp 65:82:90 --codec av1 --preset P7 --output-depth 10 --aq --aq-strength 14 --ref 4 --lookahead 32 --colormatrix bt709 --colorprim bt709 --transfer bt709 --mv-precision q-pel -i D:\t\a\test\video_temp\video_new.vpy -o D:\t\a\test\video_temp\video_new_out.av1

--------------------------------------------------------------------------------
D:\t\a\test\video_temp\video_new_out.av1
--------------------------------------------------------------------------------
vpy: VapourSynth script error.
vpy: Python exception: No module named 'mvsfunc'
vpy: Traceback (most recent call last):
vpy:   File "src\\cython\\vapoursynth.pyx", line 3233, in vapoursynth._vpy_evaluate
vpy:   File "src\\cython\\vapoursynth.pyx", line 3234, in vapoursynth._vpy_evaluate
vpy:   File "<undefined>", line 7, in <module>
vpy:   File "<frozen importlib._bootstrap_external>", line 649, in _check_name_wrapper
vpy:   File "<frozen importlib._bootstrap_external>", line 1176, in load_module
vpy:   File "<frozen importlib._bootstrap_external>", line 1000, in load_module
vpy:   File "<frozen importlib._bootstrap>", line 537, in _load_module_shim
vpy:   File "<frozen importlib._bootstrap>", line 966, in _load
vpy:   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
vpy:   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
vpy:   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
vpy:   File "C:\Portable\StaxRip-v2.38.0-x64\Apps\Plugins\VS\Scripts\havsfunc.py", line 6, in <module>
vpy:     import mvsfunc as mvf
vpy: ModuleNotFoundError: No module named 'mvsfunc'
failed to initialize file reader(s).
Failed to open input file.


Video encoding returned exit code: 1 (0x1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


   konum: StaxRip.Proc.Start() D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb içinde: satır 366
   konum: StaxRip.NVEnc.Encode() D:\Code\Github\staxrip\staxrip\Source\Encoding\NVEnc.vb içinde: satır 141
   konum: StaxRip.GlobalClass._Closure$__._Lambda$__126-8() D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb içinde: satır 367
   konum: System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   konum: StaxRip.GlobalClass.ProcessJob(String jobPath) D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb içinde: satır 376
```

**Provide information**

If there is an error message than copy the message if possible, if not then make a screenshot. After that search for the log file because it should not only contain the error message but also additional useful debug information. The log file is located in the temp folder and the temp folder is located in the same directory as the source file. The log file ends with _staxrip.log. Visit the website pastebin.com and paste the log file content there, use the auto expire feature and set it to one year.

If you can't (or don't) share your log file, give us at least this information:
- Used StaxRip version
2.38.7 over 2.38.0

log
https://pastebin.com/DtAQr8kh

**Comment by Dendraspis** [comment]
Thanks for the detailed report.

I will fix it for the next release...

**Comment by Dendraspis** [comment]
This issue will be fixed in `v2.39`...
