### ISSUE TITLE
Problem with x265-3.6+84+2

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#1457]
Hi,

I'm using Stax v.2.40
I'm waiting for 2.42 for an upgrade

Anyway, I updated the x265 executable to the latest version by Patman
 x265-3.6+84+2-f6de9241c-.Mod-by-Patman.-x64-znver4-gcc14.2.0.7z 

Seems like stax 2.40 is not compatible with it:

```
x265 [WARN]: extra unused command arguments given 

Video encoding returned exit code: 1 (0x1)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 366
   at StaxRip.x265Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in D:\Code\Github\staxrip\staxrip\Source\Encoding\x265Enc.vb:line 103
   at StaxRip.x265Enc._Closure$__28-0._Lambda$__2() in D:\Code\Github\staxrip\staxrip\Source\Encoding\x265Enc.vb:line 311
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 379
```

**Comment by Dendraspis** [comment]
It's already adjusted in `v2.42`, but thanks for the info. ☺️
