### ISSUE TITLE
Python exception: Resize erro

### ISSUE THREAD

**Issue by fransalas71** [staxrip/staxrip#1469]
What should I do to fix this error if it can be fixed? Thanks

Script Error

Python exception: Resize error: Matrix must be specified when converting to YUV or GRAY from RGB

Traceback (most recent call last):
  File "src\\cython\\vapoursynth.pyx", line 3233, in vapoursynth._vpy_evaluate
  File "src\\cython\\vapoursynth.pyx", line 3234, in vapoursynth._vpy_evaluate
  File "D:\other\staxrip.temp\VIDEO_174e2fcd-6d42-4b00-b381-a8bc13c1a8d1_temp\VIDEO_174e2fcd-6d42-4b00-b381-a8bc13c1a8d1.vpy", line 10, in <module>
    clip = core.resize.Bicubic(clip, format=vs.YUV420P10)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\\cython\\vapoursynth.pyx", line 2969, in vapoursynth.Function.__call__
vapoursynth.Error: Resize error: Matrix must be specified when converting to YUV or GRAY from RGB

**Comment by Dendraspis** [comment]
Just do what the error message tells you, for example something like:
`clip = core.resize.Bicubic(clip, format=vs.YUV420P10, matrix_s="709")`

**Comment by fransalas71** [comment]
I don't understand much, but I want to convert from RGB 12 bit to BT2020, not to 709... I don't know if I explained myself well.

**Comment by Dendraspis** [comment]
No, you did not.  😅

So look at the table from the link I have posted and choose the right one...
