### ISSUE TITLE
Cannot Preview a Script in VSEdit with QTGMC Enabled

### ISSUE THREAD

**Issue by yammes08** [staxrip/staxrip#1485]
**Describe the bug**
When creating a script in Staxrip using QTGMC, if you then load the script in VSEdit it fails with the following error:
```
Failed to evaluate the script:
Python exception: Failed to load C:\Users\Encoding\Desktop\StaxRip-v2.41.7-x64\Apps\Plugins\VS\BM3D\BM3D.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.

Traceback (most recent call last):
File "src\\cython\\vapoursynth.pyx", line 3124, in vapoursynth._vpy_evaluate
File "src\\cython\\vapoursynth.pyx", line 3125, in vapoursynth._vpy_evaluate
File "", line 16, in 
File "src\\cython\\vapoursynth.pyx", line 2860, in vapoursynth.Function.__call__
vapoursynth.Error: Failed to load C:\Users\Encoding\Desktop\StaxRip-v2.41.7-x64\Apps\Plugins\VS\BM3D\BM3D.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
```
The file `C:\Users\Encoding\Desktop\StaxRip-v2.41.7-x64\Apps\Plugins\VS\BM3D\BM3D.dll` is available at that location.

**Expected behavior**
That the video preview appears in VSEdit.

**How to reproduce the issue**

1. Load any source file
2. Add the QTGMC filter
3. Copy the code preview
4. Load the code preview in VSEdit
5. Observe the error message

**Provide information**
```
Failed to evaluate the script:
Python exception: Failed to load C:\Users\Encoding\Desktop\StaxRip-v2.41.7-x64\Apps\Plugins\VS\BM3D\BM3D.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.

Traceback (most recent call last):
File "src\\cython\\vapoursynth.pyx", line 3124, in vapoursynth._vpy_evaluate
File "src\\cython\\vapoursynth.pyx", line 3125, in vapoursynth._vpy_evaluate
File "", line 16, in 
File "src\\cython\\vapoursynth.pyx", line 2860, in vapoursynth.Function.__call__
vapoursynth.Error: Failed to load C:\Users\Encoding\Desktop\StaxRip-v2.41.7-x64\Apps\Plugins\VS\BM3D\BM3D.dll. GetLastError() returned 126. The file you tried to load or one of its dependencies is probably missing.
```
- StaxRip v2.41.7

**Comment by Andrasolin** [comment]
yes, and many other filters do not support AMD-GPU, only games, and viewing without editing, you need to read the GPU capabilities before purchasing

**Comment by Dendraspis** [comment]
Some plugins have some more dependencies, so you have to take care, that `VSEdit` and the related plugins can reach them, for example by adding them to the environment `PATH` variable.

Or you just use the`Preview` feature of StaxRip.  😅
