### ISSUE TITLE
Problem opening source file

### ISSUE THREAD

**Issue by FT001** [staxrip/staxrip#1516]
Behavior:
It gives me this DirectoryNotFoundException error while I try to  open [this](https://drive.google.com/file/d/1sq6FcCmAOUyo3Tq7J2UWwgknUR4JDr4A/view?usp=drive_link) particular .mkv source file and the error window doesn't go away no matter how many times I click ok adn there's no log file in temp folder.

Reproduce the issue:
Open the added video [file](https://drive.google.com/file/d/1sq6FcCmAOUyo3Tq7J2UWwgknUR4JDr4A/view?usp=drive_link) with this issue on staxrip (v2.42.1)  

Error information:
DirectoryNotFoundException (v2.42.1)

Could not find a part of the path 'C:\Users\FT\Videos\English lyricsSub ミライのテーマ -Original Karaoke- Mirai no Mirai Theme Song - Tatsuro Yamashita_new-00.00.07.386-00.00.31.360_temp\English lyricsSub ミライのテーマ -Original Karaoke- Mirai no Mirai Theme Song - Tatsuro Yamashita_new-00.00.07.386-00.00.31.360_new_staxrip.log'.

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\FT\Videos\English lyricsSub ミライのテーマ -Original Karaoke- Mirai no Mirai Theme Song - Tatsuro Yamashita_new-00.00.07.386-00.00.31.360_temp\English lyricsSub ミライのテーマ -Original Karaoke- Mirai no Mirai Theme Song - Tatsuro Yamashita_new-00.00.07.386-00.00.31.360_new_staxrip.log'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at StaxRip.StringExtensions.WriteFile(String instance, String path, Encoding encoding) in D:\Code\Github\staxrip\staxrip\Source\General\Extensions.vb:line 599

Notes:
The original source file opens in staxrip as expected but after trimming the video in [lossless-cut](https://github.com/mifi/lossless-cut) it doesn't open in staxrip.

**Comment by Dendraspis** [comment]
The most important question is:  Which Windows version and build do you use?

**Comment by FT001** [comment]
> The most important question is: Which Windows version and build do you use?

OS Name	Microsoft Windows 10 Pro  22H2 (OS Build19045.5011)
Version	10.0.19045 Build 19045	
Processor	Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz, 3600 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by Dendraspis** [comment]
You should go to RegEdit and check if `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` has the value `1`. Your system should support it, but it seems to be disabled.

**Comment by Dendraspis** [comment]
You're welcome.
