### ISSUE TITLE
Sound out of sync using VapourSynth/QTGMC

### ISSUE THREAD

**Issue by CanadianRyGuy** [staxrip/staxrip#1524]
StaxRip usage questions can be asked here in the Issues section or in the [Discussions section](https://github.com/staxrip/staxrip/discussions).

If I use AviSynth/AVISource/QTGMC my resulting file/audio is in sync but video looks kinda jittery/off. If I switch to VapourSynth, video looks great but my audio is out of sync. Had issues first with AviSynth being out of sync too before discovering that AVISource fixed the issue for me. If I use AVISource with VapourSynth, I get an error message (see below) If I use anything else, encoding works but audio is out of sync. Initial captures with AmaRecTV are fine with audio, video is then trimmed with Lossless-Cut (have tried Stax with both trimmed and untrimmed video though to eliminate that as a possibility). Any clarity on the issue or where to look/try is greatly appreciated! I've done like 30 test encodes doing all sorts of combinations of stuff to no avail. Log also reported Frame Mismatch:

```
--------------------------- Frame Mismatch ---------------------------

WARNING: Target file has 629953 frames, but should have 634740 frames!
Encoding was probably terminated at 99.2% with a mismatch of 4787 frames!

--------------------------- Frame Mismatch ---------------------------

Target file has 629953 frames, but should have 634740 frames!

VapourSynth/AVISource error:
Script Error

Python exception: No attribute with the name avisource exists. Did you mistype a plugin namespace or forget to install a plugin?

Traceback (most recent call last):
File "src\\cython\\[vapoursynth](https://www.videohelp.com/software/VapourSynth).pyx", line 3233, in vapoursynth._vpy_evaluate
File "src\\cython\\vapoursynth.pyx", line 3234, in vapoursynth._vpy_evaluate
File "D:\RAW CAPTURES\amarec(20240215-1117)-00.00.00.000-05.52.59.091_temp\amarec(20240215-1117)-00.00.00.000-05.52.59.091.vpy", line 37, in <module>
clip = core.avisource.AVISource(r"D:\RAW CAPTURES\amarec(20240215-1117)-00.00.00.000-05.52.59.091.avi")
^^^^^^^^^^^^^^
File "src\\cython\\vapoursynth.pyx", line 2741, in vapoursynth._CoreProxy.__getattr__
File "src\\cython\\vapoursynth.pyx", line 2564, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name avisource exists. Did you mistype a plugin namespace or forget to install a plugin?
```

**Comment by Dendraspis** [comment]
> video is then trimmed with Lossless-Cut

I recommend cutting in StaxRip when you want to reencode the video.

Can you provide the log file? 
Did you try other source filters than AVISource?

**Comment by CanadianRyGuy** [comment]
Thank you for the reply!
I'll cut in StaxRip now going forward, I don't think I really knew it was an option lol
I'll attach a log file, yes. 
I have tried all the source filters with VapourSynth and they either come out the same with audio out of sync as well or in the case of AVISource, I get the above error message (maybe it can't find the plugin file or something?). I think there were also 1 or 2 source filters that immediately caused the program to freeze and I have to restart it. I've even just converted to MKV without any filters at all and I still get audio out of sync/frames missing.
I'm not sure what you mean by my local VapourSynth...I just change it in the program...is there another VapourSynth?

**Comment by Dendraspis** [comment]
> I'll attach a log file, yes.

Still waiting.  😅 

> I think there were also 1 or 2 source filters that immediately caused the program to freeze and I have to restart it.

Depending on the source filter and the source file the filter might take some time, sometimes many minutes, to do its job.

> I'm not sure what you mean by my local VapourSynth...I just change it in the program...is there another VapourSynth?

Your error message indicates, that you're using an extermal instance of VapourSynth. Check those settings under `Settings » Frameserver`:
<img width=300 src=https://github.com/user-attachments/assets/fbbb23ab-c32c-4f1c-ba81-8a8c64c78022>

> `File "src\\cython\\[vapoursynth](https://www.videohelp.com/software/VapourSynth).pyx", line 3233`

Where did you download StaxRip from?

**Comment by CanadianRyGuy** [comment]
haha sorry about the log...attached.
I tried loading "BestSource" which is one that causes the spinning windows wheel curser, waited about 15 mins then closed the program. 
My settings show just like you pictured...which of the other 2 options under VapourSynth should I be using? Or just try both and see what happens?

As always, very much appreciate the help and guidance!

[amarec(20240425-2026)-00.00.50.894-04.25.37.679_staxrip.log](https://github.com/user-attachments/files/17664123/amarec.20240425-2026.-00.00.50.894-04.25.37.679_staxrip.log)

**Comment by CanadianRyGuy** [comment]
Just tried to use the "installed directly" option and got this message:
VapourSynth installation not found,
using portable mode instead.

 I thought everything was contained in StaxRip, but perhaps I need to install other stuff...will try and figure that out and report back!

**Comment by Dendraspis** [comment]
> Where did you download StaxRip from?

Still waiting for the answer.  😅 

Damn, the log file does not provide the information I need... but:
`.\Desktop\StaxRip-v2.42.1-x64\StaxRip-v2.42.0-x64\.` .... something went completely wrong.  😂 
And you're using `v2.42.0` and not `v2.42.1`.

**Comment by CanadianRyGuy** [comment]
I can't remember exactly where I got it from, but I think it was a legit source lol. If you have a proper place to download, I'll make sure I do a clean install. 
I just went through a few rabbit holes installing VapourSynth, Python, Visual Studio lol...way in over my head with that stuff haha. Hoping that was all unnecessary and can just stick with StaxRip.

**Comment by Dendraspis** [comment]
The original source is here on GitHub:  [Releases](https://github.com/staxrip/staxrip/releases)

A clean installation would be a good thing to start...

> I just went through a few rabbit holes installing VapourSynth, Python, Visual Studio lol...way in over my head with that stuff haha. Hoping that was all unnecessary and can just stick with StaxRip.

Yes, nothing is needed as long as you don't want to do fency stuff. Just extract `v2.42.0`, then extract `v2.42.1` in the same folder and **overwrite** the existing files and you're good to go.

**Comment by CanadianRyGuy** [comment]
I got this error message when extracting the files from the archive?

! C:\Users\ryang\OneDrive\Desktop\StaxRip-v2.42.0-x64.7z: Unknown method in StaxRip-v2.42.0-x64\Apps\FrameServer\VapourSynth\Lib\site-packages\pip\_vendor\distlib\t64-arm.exe
! C:\Users\ryang\OneDrive\Desktop\StaxRip-v2.42.0-x64.7z: Unknown method in StaxRip-v2.42.0-x64\Apps\FrameServer\VapourSynth\Lib\site-packages\pip\_vendor\distlib\w64-arm.exe
! C:\Users\ryang\OneDrive\Desktop\StaxRip-v2.42.0-x64.7z: Unknown method in StaxRip-v2.42.0-x64\Apps\FrameServer\VapourSynth\Lib\site-packages\setuptools\cli-arm64.exe
! C:\Users\ryang\OneDrive\Desktop\StaxRip-v2.42.0-x64.7z: Unknown method in StaxRip-v2.42.0-x64\Apps\FrameServer\VapourSynth\Lib\site-packages\setuptools\gui-arm64.exe

**Comment by Dendraspis** [comment]
Just update your extraction tool.  😅

I recommend [7-ZIP](https://www.7-zip.org)

**Comment by CanadianRyGuy** [comment]
OK, so yes 7-Zip worked lol
So am now properly running 2.42.1, but am still getting the same message about VapourSynth not being installed when trying to switch it to something else other than portable. Which option should it be changing to? Is that what is likely causing the original sync issue or just something to be eliminated first. 

Again thanks for the help considering so far this has all been user errors lol

**Comment by Dendraspis** [comment]
It seems that your system uses the wrong Python and/or VapourSynth version. Not sure what exactly is causing it, basically it should not happen.

You could try to run StaxRip "as Administrator", maybe this could also help.

If that doesn't help the only solution I can see right now is to remove your installed version of Python. 😕
...or to use AviSynth instead.

**Comment by CanadianRyGuy** [comment]
Maybe I'll try it on a totally different computer and see if that makes any difference. 

Just a couple questions for clarity...
1. Since I was able to get synced audio when using AVISource...should I be able to use this filter with VapourSynth? Like the error message I'm getting is that normal or do others not necessarily get this error as well? Or is there something to do with AviSynth that's causing the jittery video? Maybe I could focus on that instead of getting audio to work with VapourSynth. 
2. Is there something I could be doing when capturing with Amarectv differently that might help? Like could there be an issue with my first encodes to begin with? Something to do with variable frame rates vs constant? Or maybe i need to do some intermediary step before StaxRip to have a better file for it to work with to begin?

**Comment by Dendraspis** [comment]
> should I be able to use this filter with VapourSynth?

Yes, it is pre-defined and the call looks good. The old problem seems to be, that StaxRip can't find or use the right VapourSynth files.

> is that normal or do others not necessarily get this error as well?

You're the first one with this issue as far as I remember - at least reported.

> Or is there something to do with AviSynth that's causing the jittery video?

I don't know, should also depend on your source file.

> Is there something I could be doing when capturing with Amarectv differently that might help?

I have absolutely no experience with that, so sadly I cannot help.

> Like could there be an issue with my first encodes to begin with?

Possible ... a different codec could help, but I cannot tell.....

> Or maybe i need to do some intermediary step before StaxRip to have a better file for it to work with to begin?

Question is:  What?! I guess you have already checked the other source filters as well...

**Comment by CanadianRyGuy** [comment]
Do you know the path where the AVISource file should be? Can I just download that and put it where it needs to be?

One thing I haven't tried was maybe encoding with AviSynth/AviSource first and no filters applied to keep the video as raw as possible, then taking that file and seeing if it plays nice with VapourSynth and deinterlacing with QTGMC? Not sure what settings would be best in that scenario. 

Tried everything on another computer and having same issues, obviously I'm just not doing something right.

**Comment by Dendraspis** [comment]
Interestingly I played with some settings and source files and now I get the same error message like you ... at least almost. Very strange.

But now it's clear:
`AVISource` for VapourSynth is obsolete and not updated for years. So the better solution should be to use `FFMS2`, `BestSource` or so. Otherwise `AVISource` has to be added manually. If you are willed to do that I can give you a short instruction. But I think it is a better option to avoid it...

**Comment by CanadianRyGuy** [comment]
OK, that's good to know about VapourSynth/AVISource being a dead end...at least I can stop trying to make that work. 
Since the only thing that seems to work with audio in sync is AVISource, I'll stick with that and try to at least make the video as best as possible. 
Question on VFR vs CFR, am I correct in that .avi files are only CFR? If my file is a .avi then I shouldn't have to worry about it being VFR and any issues that might bring, right?

**Comment by Dendraspis** [comment]
> at least I can stop trying to make that work.

It can work, you just need this plugin and import the dll in your script:
https://github.com/vapoursynth/vs-avisource-obsolete/releases

> Question on VFR vs CFR, am I correct in that .avi files are only CFR?

Ask me 15 years ago.  😂   Sorry, I don't know, didn't deal with AVIs for at least one decade. But the source from above seems to be CFR, yes.

> then I shouldn't have to worry about it being VFR and any issues that might bring, right?

CFR is a lot easier to deal with, that's right.

**Comment by CanadianRyGuy** [comment]
> It can work, you just need this plugin and import the dll in your script:
`https://github.com/vapoursynth/vs-avisource-obsolete/releases
Sorry, may I ask how to do that? I guess it's worth giving it a try as another possibility.

**Comment by Dendraspis** [comment]
You can put the DLL file into `.\Settings\Plugins\VapourSynth` so it gets automatically included or you simple load it right before your filter call via:
`core.std.LoadPlugin(r"A:\Path\To\File.dll", altsearchpath=True)`

Then just call the filter like shown here:
https://github.com/vapoursynth/vs-avisource-obsolete/blob/master/docs/avisource.rst

**Comment by CanadianRyGuy** [comment]
Thanks! Trying an encode right now and so far so good, no error message or anything so at least doing better than before lol. I'll let you know how it turns out in a couple of hours.

**Comment by CanadianRyGuy** [comment]
Holy Moly! We might have a winner...first encode seems to be a success! Will have to do some more tests to make sure its really a solution lol

**Comment by Dendraspis** [comment]
Tests successful?
Can I ask you how your filter call looks like?

**Comment by CanadianRyGuy** [comment]
Yeah I think they're looking pretty good!
I don't mind at all but you may have to show me how to do that lol

**Comment by Dendraspis** [comment]
Sorry for the late response.
So you didn't manage to execute it on your own?

**Comment by CanadianRyGuy** [comment]
Hello!
Sorry to bother you again, I have been encoding files just fine since you helped me solve my audio sync issues and was using VapourSynth/AVISource without issues, until now lol. I have now started receiving an error message like below when trying to use AVISource with Vapoursynth, nothing else has changed with any of the settings I use in StaxRip nor how I've been capturing files in AmarecTV. Any ideas why I'm seeing this now and what might have changed? And more importantly, what I can do? lol

Script Error

Python exception: AVISource: couldn't locate a decompressor for fourcc ULY2

Traceback (most recent call last):
  File "src\\cython\\vapoursynth.pyx", line 3233, in vapoursynth._vpy_evaluate
  File "src\\cython\\vapoursynth.pyx", line 3234, in vapoursynth._vpy_evaluate
  File "D:\RAW CAPTURES\amarec(20250113-1556)-00.00.07.508-06.13.01.077.avi_temp\amarec(20250113-1556)-00.00.07.508-06.13.01.077.vpy", line 8, in <module>
    clip = core.avisource.AVISource(r"D:\RAW CAPTURES\amarec(20250113-1556)-00.00.07.508-06.13.01.077.avi")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\\cython\\vapoursynth.pyx", line 2969, in vapoursynth.Function.__call__
vapoursynth.Error: AVISource: couldn't locate a decompressor for fourcc ULY2

**Comment by Dendraspis** [comment]
Did you update StaxRip recently?  If so, from which version did you upgrade?

**Comment by CanadianRyGuy** [comment]
I was using 2.42.1 when it first started happening and then I upgraded to latest version and it was still happening.

**Comment by Dendraspis** [comment]
Since `v2.44` there is a new version of `VapourSynth`, maybe that has to do something with your issue.
`ULY2` sounds also a bit unusual...   But right now I'm pretty clueless.  😕

**Comment by CanadianRyGuy** [comment]
Hmm, any chance you could explain where to even start looking? I've played around with a few versions of StaxRip and on different computers and keep getting the same error message, so my thinking is that something must have changed with the original capture recording? Newer ones get the error and older ones don't, so that leads me to believe its the file itself that is causing it? Is it an audio thing or video? Maybe I can try and pinpoint if an option or setting changed in AmarecTV.
