### ISSUE TITLE
System.ArgumentOutOfRangeException: Value to add was out of range.

### ISSUE THREAD

**Issue by Cyberavater** [staxrip/staxrip#168]
--------------------------- AviSynth Script ---------------------------

# can be configured at: Tools > Settings > Source Filters

---------------------- Source Script Information ----------------------

------------------------------ Exception ------------------------------

System.ArgumentOutOfRangeException: Value to add was out of range.
Parameter name: value
   at System.DateTime.Add(Double value, Int32 scale)
   at StaxRip.ServerInfo.GetInfoText(Int32 position) in D:\Projekte\VB\staxrip\General\FrameServer.vb:line 77
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 148
   at StaxRip.GlobalClass.ProcessJobs() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 98

**Comment by Dendraspis** [comment]
I doubt this will be enough information for @stax76 to work with. Why don't you use the given template?

**Comment by Cyberavater** [comment]
It's fixed after manually adding DGIndex.
