### ISSUE TITLE
System.OverflowException using Video Comparison tool

### ISSUE THREAD

**Issue by therealt3nzin** [staxrip/staxrip#196]
**Describe the bug**
Getting a System Overflow Exception on a completely fresh portable install of 2.1.1.3 when using the Video Comparison tool. Tested on 3 separate machines, all get the same error.

**How to reproduce the issue**

Open any video file with the Video Comparison tool & StaxRip crashes immediately.

**Provide information**

```
-------------------------------- Exception --------------------------------

System.OverflowException: Arithmetic operation resulted in an overflow.
   at StaxRip.VideoComparisonForm.VideoTab.Draw()
   at StaxRip.VideoComparisonForm.VideoTab.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by therealt3nzin** [comment]
Bug present in 2.1.1.3 & 2.1.1.4

**Comment by stax76** [comment]
New beta is now online.

https://staxrip.readthedocs.io/introduction.html#beta

**Comment by therealt3nzin** [comment]
Thanks Stax, working great now!

**Comment by stax76** [comment]
OK, thanks for reporting and testing.
