### ISSUE TITLE
x265.exe cannot read input <-> 

### ISSUE THREAD

**Issue by Asphxiated** [staxrip/staxrip#290]
**Describe the bug**
I can get Staxrip 2.1.3.0, 2.0.8.0, and 2.0.6.0 to work if I choose AviSynth/VapourSynth as the decoder and "automatic" for piping but if I try to use FFmpeg (DXVA2) for the decoder and any of the options for piping including automatic and none both produce and error that basically states:

` Video encoding using x265 3.2+9-971180b100f8 Patman (2.0.6.0)

Video encoding using x265 3.2+9-971180b100f8 Patman failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

--------- Video encoding using x265 3.2+9-971180b100f8 Patman ---------

"C:\Program Files\StaxRip-x64-2.0.6.0-stable\Apps\Encoders\ffmpeg\ffmpeg.exe" -threads 1 -hwaccel dxva2 -i "D:\Videos\TOS 2160p HDR.mkv" -f yuv4mpegpipe -strict -1 -loglevel fatal -hide_banner - | "C:\Program Files\StaxRip-x64-2.0.6.0-stable\Apps\Encoders\x265\x265.exe" --crf 19 --output-depth 10 --rect --amp --limit-modes --hevc-aq --me star --max-merge 4 --fades --frame-threads 3 --master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)" --colorprim bt2020 --colormatrix bt2020nc --transfer smpte2084 --range limited --max-cll "4851,3586" --hdr --hdr-opt --repeat-headers --hrd --aud --opt-qp-pps --opt-ref-list-length-pps --input-depth 10 --deblock -2:-3 --frames 94236 --y4m --output "D:\Videos\TOS 2160p HDR_temp\TOS.HDR.2160p.HEVC.10-bit.DD+.Atmos.5.1.mkv_out.hevc" -

x265 [error]: unable to open input file <->

StaxRip.ErrorAbortException: Video encoding using x265 3.2+9-971180b100f8 Patman failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

--------- Video encoding using x265 3.2+9-971180b100f8 Patman ---------

"C:\Program Files\StaxRip-x64-2.0.6.0-stable\Apps\Encoders\ffmpeg\ffmpeg.exe" -threads 1 -hwaccel dxva2 -i "D:\Videos\TOS 2160p HDR.mkv" -f yuv4mpegpipe -strict -1 -loglevel fatal -hide_banner - | "C:\Program Files\StaxRip-x64-2.0.6.0-stable\Apps\Encoders\x265\x265.exe" --crf 19 --output-depth 10 --rect --amp --limit-modes --hevc-aq --me star --max-merge 4 --fades --frame-threads 3 --master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)" --colorprim bt2020 --colormatrix bt2020nc --transfer smpte2084 --range limited --max-cll "4851,3586" --hdr --hdr-opt --repeat-headers --hrd --aud --opt-qp-pps --opt-ref-list-length-pps --input-depth 10 --deblock -2:-3 --frames 94236 --y4m --output "D:\Videos\TOS 2160p HDR_temp\TOS.HDR.2160p.HEVC.10-bit.DD+.Atmos.5.1.mkv_out.hevc" -

x265 [error]: unable to open input file <->

   at StaxRip.Proc.Start() in D:\Projekte\VB\staxrip\General\Proc.vb:line 340
   at StaxRip.x265Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in D:\Projekte\VB\staxrip\Encoding\x265Enc.vb:line 66
   at StaxRip.x265Enc.Encode() in D:\Projekte\VB\staxrip\Encoding\x265Enc.vb:line 43
   at StaxRip.GlobalClass.ProcessVideo() in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 228
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VB\staxrip\General\GlobalClass.vb:line 138`

but if I take that code and throw it into a CLI (command.exe) with a -pix_fmt yuv420p10le it will work, its been suggested to me on doom9 that maybe something changed in FFmpeg between the newest version and 2.0.8.0 so I tried multiple versions and got the same result with all of them. If you need an error from the most recent version I can do that but they say the same thing, that x265.exe cannot read the input <-> or (STDOUT, I believe? maybe STDIN but either way it should work without the -pix_format FFmpeg option, and I see no way of put in that option for FFmpeg through staxrip.

**Expected behavior**
I expect the video to be decoded by my videocard and that bitstream to be fed to x265.exe for encoding and then muxing together the resulting file.

**How to reproduce the issue**

Test if the bug happens only with a particular source file or source file type, if so then upload a sample file. If you cannot upload the file then please install the application https://github.com/stax76/MediaInfo.NET and post media info about the source file.

If the issue happens only under special conditions then please describe how this conditions can be reproduced:

If you do a 10-bit HDR MKV yuv420p10le file input and choose x265 as the encoder, in the encoder options where it says "decoder" set it to FFMpeg (DXVA2) and set piping to anything, I started with FFmpeg, then vspipemod and then nothing and then automatic and nothing worked. I finally set decoder to Avisynth/VapourSynth and piping to automatic and it the file finally starts to encode with this as the command (in 2.0.6.0):

`--------- Video encoding using x265 3.2+9-971180b100f8 Patman ---------

"C:\Program Files\StaxRip-x64-2.0.6.0-stable\Apps\Support\avs2pipemod\avs2pipemod64.exe" -y4mp "D:\Videos\Altered Carbon S01E07 2160p HDR_temp\Altered.Carbon.S01E07.HDR.2160p.HEVC.10-bit.DD+.Atmos.5.1.mkv.avs" | "C:\Program Files\StaxRip-x64-2.0.6.0-stable\Apps\Encoders\x265\x265.exe" --crf 19 --output-depth 10 --hevc-aq --me star --max-merge 4 --bframes 3 --fades --frame-threads 3 --master-display "G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)" --colorprim bt2020 --colormatrix bt2020nc --transfer smpte2084 --range limited --max-cll "4851,3586" --hdr --hdr-opt --repeat-headers --aud --input-depth 10 --deblock -2:-3 --no-strong-intra-smoothing --frames 94236 --y4m --output "D:\Videos\Altered Carbon S01E07 2160p HDR_temp\Altered.Carbon.S01E07.HDR.2160p.HEVC.10-bit.DD+.Atmos.5.1.mkv_out.hevc" -`

**Provide information**

I don't have a screen shot but here is a log of a 2.1.3.0 crash: [pastebin](https://pastebin.com/6qvhE2aU)

**I have already posted about this on Doom9 as I said before and they seem to be having the same issues, look at the last page or two of the official support thread for staxrip on there, my posts are under BobbyBoberton

**Additional context**

if staxrip would put in a -pix_fmt option to FFmpeg this seems like it can be worked around but maybe I am just doing something wrong, I am not sure.

**Please be as clear and as detailed as possible**

**Comment by stax76** [comment]
When the x265 option Decoder FFmpeg (DXVA2) is used then avisynth/vapoursynth is not used at all but rather the source file is opened directly by ffmpeg and therefore the pipe option is not relevant because piping is done in order to pipe data from avisynth/vapoursynth to x265.

The problem is when the ffmpeg option -hwaccel dxva2 is used then as you pointed out it's also necessary to define the -pix_fmt option, this is a bug in staxrip, I don't understand why ffmpeg requires it in this case, without -hwaccel option -pix_fmt is not necessary.

In order to fix it staxrip would have to generate the -pix_fmt argument based on media info of the source file, it's more likely that we rather remove the Decoder FFmpeg (DXVA2) feature because it's too much work to generate the -pix_fmt argument.

The second problem is that the staxrip docs currently don't explain how hardware decoding can be used with avisynth/vapoursynth, here is a screenshot:

https://postimg.cc/HV8SCNDC

**Comment by Asphxiated** [comment]
well its still "piped" with "|" via ffmpeg.exe -hwaccel dxva2 -i INPUT - | x265.exe 

but wouldn't it be possible to add a menu next to the decoder option if FFmpeg (DXVA2) is chosen then you must choose a -pix_fmt option as well? It only needs to be the format you are trying to encode to, not the incoming format, I have already asked ffmpeg about that awhile ago. So instead of disabling hwaccel for decoding why not just do that? At some point, I get its low priority.

**Comment by Asphxiated** [comment]
This might clear things up with regard to -pix_fmt from doom9: 


Originally Posted by BobbyBoberton: Um ok, maybe I misunderstood the documentation but I thought -pix_fmt was to explicitly tell FFmpeg what the format of the incoming file, not the output format, but I guess that makes sense because if I drop the -pix_fmt yuv420p10le then it defaults to yuv420p so ok, thank you.

ANSWER:
It depends where you put the option. And what kind of file it is.

If you want to specify any properties for the input file, you need to put them before the -i option. Anything after the -i option specifies the output.

An MKV file with presumably h264 or h265 inside, you cannot override the "incoming" format anyway, the encoded bitstream clearly defines that, so that isn't often useful.

So yeah, you are specifying the output format, which is going to be passed to x265. Although if your input was already 10-bit, it should've just stuck with that. So your input must've been something else then?

**Comment by Asphxiated** [comment]
I can code a bit, seems like you used visual basic at least for the GUI part, if you could point out where in the source files I should start looking for options menu's and what code they generate I can try to patch this myself.

**Comment by Dendraspis** [comment]
Sorry, but I doubt that *I can code a bit* is enough for this task. If it was sort of simple in any way, @stax76 would have fixed it already.

----

@stax76 
> In order to fix it staxrip would have to generate the -pix_fmt argument based on media info of the source file, it's more likely that we rather remove the Decoder FFmpeg (DXVA2) feature because it's too much work to generate the -pix_fmt argument.

Not 100% sure, but it seems like FFmpeg has already an automatism integraded. From its [docs](https://ffmpeg.org/ffmpeg.html#Advanced-Video-options):
> -pix_fmt[:stream_specifier] format (input/output,per-stream)
Set pixel format. [..] **If pix_fmt is a single +, ffmpeg selects the same pixel format as the input** (or graph output) and automatic conversions are disabled.

So if `-hwaccel dxva2` is used, StaxRip should just add `-pix_fmt +` and FFmpeg will set the neccessary option by itself. Wouldn't this fix the problem?

**Comment by Asphxiated** [comment]
I was trying to be humble about it but yes, that would be exactly what is needed if it actually works like that, which is not that different from my suggestion, just uses the newer ffmpeg coding to get it done.  If -pix_fmt now works this way then I assume they did the + thing for apps/situations like this where ffmpeg is used to pipe to an encoder.

**Comment by Dendraspis** [comment]
> If -pix_fmt now works this way then I assume they did the + thing for apps/situations like this where ffmpeg is used to pipe to an encoder.

The question is: Why is the `+` not the default behaviour and why does it have to be set?

>  [..] there is no need to determine the input source pixel format because [..] 

His problem was not setting the input but the output format, which should be equal to the input format - at least as long as you use is as a decoder to pipe the source file to another app.
Im my opinion `-pix_fmt +` should do the trick.

> After thinking about it somemore this + thing will only work if you want to keep the same pix_fmt and not encoding 8-bit SDR in 10-bit SDR or something like that which is ok just not ideal for me.

This translation should typically be done by the encoder. 🤔

**Comment by Asphxiated** [comment]
> > If -pix_fmt now works this way then I assume they did the + thing for apps/situations like this where ffmpeg is used to pipe to an encoder.
> 
> The question is: Why is the `+` not the default behaviour and why does it have to be set?
> 
> > [..] there is no need to determine the input source pixel format because [..]
> 
> His problem was not setting the input but the output format, which should be equal to the input format - at least as long as you use is as a decoder to pipe the source file to another app.
> Im my opinion `-pix_fmt +` should do the trick.
> 
> > After thinking about it somemore this + thing will only work if you want to keep the same pix_fmt and not encoding 8-bit SDR in 10-bit SDR or something like that which is ok just not ideal for me.
> 
> This translation should typically be done by the encoder. 🤔

You very well could be correct, but this is what I was told by the people over at ffmpeg but I forget that you are effectively dealing with a y4m stream from ffmpeg which is by default assumed to be 8-bit pixel depth according to the x265.exe help files so I think as long as you make sure you are informing the encoder that the incoming stream is 10-bit and not 8-bit then your solution should work for all cases, whether yuv420p or yuv420p10le `-pix_fmt +` should fix the issue. 

Also yes, there should be some discussion as to why this is not default behavior for ffmpeg if they built this option for -pix_fmt why not set it to + by default unless otherwise specified? I guess I'll have to ask them.

**Comment by stax76** [comment]
@Dendraspis 

I tried  `-pix_fmt +` on the command line at several locations but it did not work?

**Comment by Asphxiated** [comment]
> @Dendraspis
> 
> I tried `-pix_fmt +` on the command line at several locations but it did not work.

That is weird because right from the ffmeg documentation it says:

```
-pix_fmt[:stream_specifier] format (input/output,per-stream)
Set pixel format. Use -pix_fmts to show all the supported pixel formats. If the selected pixel format can not be selected, ffmpeg will print a warning and select the best pixel format supported by the encoder. If pix_fmt is prefixed by a +, ffmpeg will exit with an error if the requested pixel format can not be selected, and automatic conversions inside filtergraphs are disabled. **If pix_fmt is a single +, ffmpeg selects the same pixel format as the input (or graph output) and automatic conversions are disabled.**
```

maybe you need to add a stream specifier like 

```
-pix_fmt :0 + 
```

This seems like it is the solution, it just needs to be implemented properly.

**Comment by Asphxiated** [comment]
Just checking, did you mean Sunday today, or Sunday next week since in your area of the world it would have been close it if not Sunday already. Just wanting clarification for watching for a new release, obviously take your time, you fixed it ;)

**Comment by Asphxiated** [comment]
would totally be fine with a beta too ;)

**Comment by Asphxiated** [comment]
Just tried out the beta, seems to be working as intended on my system for hardware accel decoding, thanks for the work and beta @stax76

**Comment by stax76** [comment]
Thanks @Asphxiated and @Dendraspis.
