### ISSUE TITLE
i have now received 4 errors in a row

### ISSUE THREAD

**Issue by YOURMOMMYFACE** [staxrip/staxrip#356]
First I got that error you closed and said to use beta
Use beta and path was not found, had to fix that error and start over
Then after all that dghable is not found
Went back to a older version and now I get

Failed to load job file:

C:\Users\christoph\AppData\Roaming\StaxRip\Jobs.dat

Type 'StaxRip.Job' in Assembly 'StaxRip, Version=2.0.2.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.

System.Runtime.Serialization.SerializationException: Type 'StaxRip.Job' in Assembly 'StaxRip, Version=2.0.2.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitReadConstructor(Type objectType, ISurrogateSelector surrogateSelector, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Init(Type objectType, String[] memberNames, Type[] memberTypes, ISurrogateSelector surrogateSelector, StreamingContext context, ObjectManager objectManager, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, Boolean bSimpleAssembly)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at StaxRip.Job.GetJobs() in C:\Users\frank\Daten\Projekte\VB\staxrip\General\Job.vb:line 79

**Comment by stax76** [comment]
And I received 4 lines in a row of poor bug report. Issue templates exist for a reason.

**Comment by JJKylee** [comment]
OK. Seeing that this person is mentioning _dghable_, I guess he/she is talking about **DGTonemap**.
But, hey, @YOURMOMMYFACE , DGTonemap is NOT a default filter shipped with StaxRip.
It's something YOU need to 'install' and set up in filter profiles.

I wrote a [howto post in the Doom9 thread](https://forum.doom9.org/showthread.php?p=1913616#post1913616), but since it tweaks the program structure, maybe your filter was gone after you upgraded StaxRip. That's probably why you have errors.

I'm gonna write an updated version of the howto in the wiki section of this repo, so please be patient.

**Comment by stax76** [comment]
It's removed from the defaults, the problem is that it's a user settings which some people invested much time.
