### ISSUE TITLE
2.1.7.8: First time launch pops up an error

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#490]
**Describe the bug**
While launching 2.1.7.8 Beta (with `StaxRip.exe` replaced with the hotfix) the **first** time, I ran into this error.

![StaxRip_2 1 7 8_first-launch_error_20210206](https://user-images.githubusercontent.com/3157518/107130544-57531800-6883-11eb-9d3c-00bc922651f8.jpg)

```
------------------------- System Environment -------------------------

StaxRip    : 2.1.7.8
Windows    : Windows 10 Home 2009
Language   : English (United States)
CPU        : Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
GPU        : NVIDIA GeForce GTX 1060 with Max-Q Design, Intel(R) HD Graphics 630
Resolution : 2560 x 1080
DPI        : 120
Code Page  : 65001

------------------------------ Exception ------------------------------

System.NullReferenceException: Object reference not set to an instance of an object.
   at StaxRip.FrameServerHelp.IsAviSynth()
   at StaxRip.FrameServerHelp.AviSynthToolPath()
   at StaxRip.Package.LoadConfAll()
   at StaxRip.Package._Closure$__._Lambda$__489-98()
   at StaxRip.GlobalClass._Closure$__188-0._Lambda$__0()
```

If I force close the main window ingoring the errors and relaunch it, the error disappears and does not pop up again.

**How to reproduce the issue**

1. Download `StaxRip-x64-2.1.7.8-Beta.7z` and `StaxRip.exe` (hotfix binary), and unzip them.
2. Launch StaxRip.

**More information**

IMHO, this is because `Settings.dat` is missing on the first launch. By contrast, overwriting binaries (except for Apps folder) on the existing ones does not raise this issue on the first launch of this new version.

For your reference, I have an installed AviSynth 3.7.0 on `C:\WINDOWS\system32\AviSynth.dll`.

**Comment by JJKylee** [comment]
A [hot fix](https://github.com/staxrip/staxrip/issues/473#issuecomment-774554483) resolved this issue.
