### ISSUE TITLE
NVEnc Error (2.0.1.0) GPU is not supported. 

### ISSUE THREAD

**Issue by nulledone** [staxrip/staxrip#5]
So somehow I can still successfully convert videos on 1.7 but not 2.0.1.0, here's the log. 

NVEnc Error (2.0.1.0)

H.265/HEVC isn't supported by the graphics card.

StaxRip.ErrorAbortException: H.265/HEVC isn't supported by the graphics card.
   at StaxRip.NVEnc.Encode() in C:\Users\frank\Daten\Projekte\VB\staxrip\Encoding\NVEnc.vb:line 72
   at StaxRip.GlobalClass.ProcessVideo() in C:\Users\frank\Daten\Projekte\VB\staxrip\General\GlobalClass.vb:line 227
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in C:\Users\frank\Daten\Projekte\VB\staxrip\General\GlobalClass.vb:line 137
 
1050Ti, 
Windows 10 1607

**Comment by stax76** [comment]
It's probably a nvencc issue, you can try an older nvencc built.

https://github.com/rigaya/NVEnc/issues

**Comment by nulledone** [comment]
Using 4.41 (latest) fixed it.
