### ISSUE TITLE
Preview window in latest ver. 2.3.0 shows error - Unable to cast COM object...

### ISSUE THREAD

**Issue by tutak-kat** [staxrip/staxrip#640]
Hi, hope that this is not a bug but just some restriction of my C: disk.

so I'm using staxrip for years without problems - thanks for a such a great program, and it is installed on my main PC on D disk.
I just install this new version on my laptop - for the first time - but since laptop has only 1 disk - SSD - it is not divided in 2 partitions, so I installed it on C:\users........\my documents.

I run win7sp1x64

Programs runs correctly but when I tried to open CUT or PREVIEW window I got the following error:

InvalidCastException (2.3.0)

Unable to cast COM object of type 'System.__ComObject' to interface type 'DirectN.ID2D1DeviceContext'. 
This operation failed because the QueryInterface call on the COM component for the interface with 
IID '{E8F7FE7A-191C-466D-AD95-975678BDA998}' failed due to the following error: 
No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).

System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'DirectN.ID2D1DeviceContext'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{E8F7FE7A-191C-466D-AD95-975678BDA998}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at StaxRip.VideoRenderer.CreateGraphicsResources() in D:\Code\Github\staxrip\staxrip\Source\Video\VideoRenderer.vb:line 287
   at StaxRip.VideoRenderer.Draw() in D:\Code\Github\staxrip\staxrip\Source\Video\VideoRenderer.vb:line 102
   at StaxRip.PreviewForm.pnVideo_Paint(Object sender, PaintEventArgs e) in D:\Code\Github\staxrip\staxrip\Source\Forms\PreviewForm.vb:line 1238
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Any idea how to resolve this issue?

Thanks

**Comment by stax76** [comment]
The error message tells that the ID2D1DeviceContext interface is not available, this is a Direct2D interface, the system requirements of Direct2D are listed here:

https://docs.microsoft.com/en-us/windows/win32/direct2d/direct2d-portal
