### ISSUE TITLE
Two new linked problems with Preview and External player when Trim is used

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#70]
Hi Stax, Revan,

Last beta 2.0.4.6 (and maybe 2.0.4.5) has this problem:

1. create a project and select a single range (Trim) in preview window
2. open external player (Key E). The player will Play WHOLE FILE, not range !! This is the first problem.
3. close player, reopen player (Key E), close it again, you're back in the preview window, press R to reload : Staxrip crashes with the following report:

TargetInvocationException (2.0.4.6)

Exception has been thrown by the target of an invocation.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Native handle is 0.
Parameter name: handle
   at System.Drawing.Image.SetNativeImage(IntPtr handle)
   at System.Drawing.Bitmap.FromGDIplus(IntPtr handle)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at StaxRip.AVIFile.GetBMPFromDib(IntPtr pDIB) in D:\Projekte\VB\staxrip\General\AVIFile.vb:line 147
   at StaxRip.AVIFile.GetBitmap() in D:\Projekte\VB\staxrip\General\AVIFile.vb:line 139
   at StaxRip.VideoDrawer.Draw(Graphics g) in D:\Projekte\VB\staxrip\General\VideoDrawer.vb:line 27
   at StaxRip.PreviewForm.pVideo_Paint(Object sender, PaintEventArgs e) in D:\Projekte\VB\staxrip\Forms\PreviewForm.vb:line 1000
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by 44vince44** [comment]
Correction to the report above:
the crash when reloading in the preview window is NOT related to trim:
Open any file, open preview, press E to open player, close player, you are back on preview,
press R, then staxrip crashes.

**Comment by stax76** [comment]
Hi, I'll upload a fix later today.

**Comment by 44vince44** [comment]
ok thanks, i'll test it hopefully tonight.

**Comment by stax76** [comment]
It's now available:

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by 44vince44** [comment]
OK I understand the new logic ! So now it is working !
It is good idea for those who don't want to use mpv.net (not for me, I prefer mpv.net). 
But there is a problem: when opening preview for the first time, the app manager asks to locate any MPC that couldn't be located, and prevents the preview window from opening. I guess the app manager should open if F10 is pressed from preview, and not when preview is opened.

**Comment by stax76** [comment]
Sorry about these issues, I've uploaded another build to fix it.

**Comment by 44vince44** [comment]
Thank you very much Stax, everything works OK now!
