### ISSUE TITLE
A generic error occurred in GDI+

### ISSUE THREAD

**Issue by Kidsnd274** [staxrip/staxrip#703]
Got this error at the final step when it's muxing the file together. Anyone know what does this mean?

------------------------------ Exception ------------------------------

System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at System.Drawing.Graphics.MeasureString(String text, Font font, Int32 width)
   at StaxRip.TaskDialogBaseForm.TaskDialogPanel.OnLayout(LayoutEventArgs levent) in D:\Code\Github\staxrip\staxrip\Source\UI\TaskDialogBaseForm.vb:line 95
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at StaxRip.TaskDialog`1.Init() in D:\Code\Github\staxrip\staxrip\Source\UI\TaskDialog.vb:line 98
   at StaxRip.TaskDialog`1.Show() in D:\Code\Github\staxrip\staxrip\Source\UI\TaskDialog.vb:line 443
   at StaxRip.MainModule.MsgError(String title, String content, IntPtr handle) in D:\Code\Github\staxrip\staxrip\Source\General\General.vb:line 1193
   at StaxRip.MainModule.MsgError(String title, String content) in D:\Code\Github\staxrip\staxrip\Source\General\General.vb:line 1174
   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 319
   at StaxRip.MkvMuxer.Mux() in D:\Code\Github\staxrip\staxrip\Source\General\Muxer.vb:line 616
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 378
   at StaxRip.GlobalClass.ProcessJobsRecursive() in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 232

**Comment by 44vince44** [comment]
We could, if we have the entire log, so we get, among other things:
- version of staxrip
- kind of file used
- which muxer (Mp4box or MKVmerge)
- and many more MISSING INFORMATION

**Comment by Kidsnd274** [comment]
Here's the entire log
[Kaguya-sama Love Is War S02E01_new_staxrip.log](https://github.com/staxrip/staxrip/files/6451412/Kaguya-sama.Love.Is.War.S02E01_new_staxrip.log)

**Comment by Dendraspis** [comment]
> Got this error at the final step when it's muxing the file together. Anyone know what does this mean?

Don't get me wrong, but this is an issue tracker, not a forum or discussion platform.
In order to help we need to reproduce the problem, here your error message, so as many detailed information as possible are needed.

- Did you change the **Console font** in the settings?
- Does it also happen with fresh settings?  (delete/rename *settings.dat*)

**Comment by 44vince44** [comment]
@Dendraspis @Kidsnd274 
There are SO MANY (probably useless) attachements: 203 fonts attached !!!!!!!!!!!

The muxing command line is **41 THOUSAND CHARACTERS LONG !!!!**

41.667 CHARACTERS !!!!! what OS CAN EVER HANDLE THAT.

@Kidsnd274 Staxrip is a command line based software. The really exagerated, excessive amount of attachements is the cause of the error. Please remove unnecessary attachements before processing/muxing.

**Comment by Dendraspis** [comment]
To be precise there occurs an error, but the immense parameter length causes StaxRip to crash because it can't handle the error message.  🥴 

But I'm pretty sure using a *normal* amount of fonts should fix all issues.

**Comment by JJKylee** [comment]
> [Kaguya-sama Love Is War S02E01_new_staxrip.log](https://github.com/staxrip/staxrip/files/6451412/Kaguya-sama.Love.Is.War.S02E01_new_staxrip.log)

I couldn't help but exclaim "Wow...!!!!" when I opened up the log. 😓
Seriously, are those fonts _all_ necessary for your _**English**_ ass subtitle, @Kidsnd274?
I'm doubtful. 🤔

Anyway, if you _do_ need all those fonts, maybe you better do the muxing job in _MKVToolNix GUI_ not on the console as is done by StaxRip. Hmm... 🤔
