### ISSUE TITLE
Demuxed video elementary streams should not be the %source_file% for ffms2 source filters in VapourSynth

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#749]
## [Description]

Currently, when `Demux Video` is enabled in _Options_ > _Video_, extracted **video elementary streams** such as `h264` and `h265` are automatically put as the `%source_file%` in StaxRip. But this results in issues when the source filter is **ffms2** (and **FFVideoSource** in AviSynth).

**ffms2** manual clearly states that

> Because of LAVF's demuxer, most raw streams (such as elementary h264 and other mpeg video streams) will fail to work properly.

(And since `LWLibavVideoSource` (AVS) and `lsmas.LWLibavSource` (VS) in **L-SMASH-Works** use `libavformat`(=LAVF) as demuxer, they are not totally free from this problem.)

In working with timestamps extracted from MKV, I've found that the following _index generation failure_ error appears with many MKV source files.

![StaxRip_2 6 44_Incorrect_source-file_when_Demux-Video_option_enabled_20210718](https://user-images.githubusercontent.com/3157518/126080902-66580980-ba51-4c07-80e1-638577067f02.png)

```
Script Error

Python exception: Source: The index does not match the source file

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2242, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 2243, in vapoursynth.vpy_evaluateScript
  File "D:\Test\Two audio sample_temp\Two audio sample_new_source.vpy", line 8, in <module>
    clip = core.ffms2.Source(r"D:\Test\Two audio sample_temp\Two audio sample.h264", cachefile=r"D:\Test\Two audio sample_temp\temp.ffindex", timecodes=tcFile) if os.path.exists(tcFile) else core.ffms2.Source(r"D:\Test\Two audio sample_temp\Two audio sample.h264", cachefile=r"D:\Test\Two audio sample_temp\temp.ffindex")
  File "src\cython\vapoursynth.pyx", line 2067, in vapoursynth.Function.__call__
vapoursynth.Error: Source: The index does not match the source file
```

(Side note: once this error occurs in, eg., VapourSynth, I can't switch to AviSynth.)

The same issue does not occur with the _same_ source file if `Demux Video` is disabled and thus the original MKV (**_not the demuxed elementary stream_**) is put as the `%source_file%` in the script.

And I have confirmed that the same issue also arises with other container formats like **_MP4_** and **_ts_**.

## [Expected behavior]

Elementary streams should not be put as the `%source_file%` in place of the input file even if they are demuxed according to the Options setting.

## [How to reproduce the issue]

Version: v2.6.44 (or later)

1. Make sure demux of input file types is given priority in _Tools_ > _Settings_ > _Preprocessing_
2. Select `Manual Workflow` template
3. Switch to VapourSynth
4. Set source filter to `ffms2`
5. Enable _Options_ > _Video_ > _Demux Video_
6. Load any MKV/MP4/ts file

**Comment by JJKylee** [comment]
I've confirmed that this error arises 100% in VapourSynth, but randomly arises in AviSynth.
Since it seems more like a tool issue with `ffms2` and also because we haven't received any issue reports regarding this matter, I'm closing this thread for now.
I'll take time to look further into this.
