### ISSUE TITLE
Staxrip stops processing with a file containing DVBSUB track.

### ISSUE THREAD

**Issue by Jack0121** [staxrip/staxrip#833]
I am running STAXRIP 2.10.0
When I try to encode a file with DVBSUB track - the encode raises an exception.
Here is a sample file:
[sample.mkv.zip](https://github.com/staxrip/staxrip/files/8016603/sample.mkv.zip)

Here is what the tracks look like in MKVToolNix
![MKVToolNix-ViewOfFile](https://user-images.githubusercontent.com/99195804/152820952-3e72c9a9-d9f4-4033-8000-66b7760e8c92.PNG)

If remove the DVBSUB track - everything works beautifully.

Is there a fix for this?

Here is the error message from StaxRip:
```
Error Muxing to MKV (v2.10.0)

Muxing to MKV returned exit code: 2 (0x2)


---------------------------- Muxing to MKV ----------------------------

mkvmerge 61.0

C:\bin\StaxRip-v2.10.0-x64\Apps\Support\MKVToolNix\mkvmerge.exe -o D:\Media.done\sample.mkv C:\temp\sample_temp\sample_out.hevc --audio-tracks 0 --language 0:eng --sync 0:-1763 --default-track 0:0 --forced-track 0:0 "C:\temp\sample_temp\ID1 -1763ms English.aac" --no-audio --no-video --no-chapters --no-attachments --no-track-tags --no-global-tags --subtitle-tracks 2 --forced-track 2:0 --default-track 2:1 --language 2:eng --track-name "2:" C:\Users\araz\Downloads\sample.mkv --title "Channel 4 HD" --ui-language en

mkvmerge v61.0.0 ('So') 64-bit
Error: The type of file 'C:\temp\sample_temp\ID1 -1763ms English.aac' could not be recognized.

StaxRip.ErrorAbortException: Muxing to MKV returned exit code: 2 (0x2)


---------------------------- Muxing to MKV ----------------------------

mkvmerge 61.0

C:\bin\StaxRip-v2.10.0-x64\Apps\Support\MKVToolNix\mkvmerge.exe -o D:\Media.done\sample.mkv C:\temp\sample_temp\sample_out.hevc --audio-tracks 0 --language 0:eng --sync 0:-1763 --default-track 0:0 --forced-track 0:0 "C:\temp\sample_temp\ID1 -1763ms English.aac" --no-audio --no-video --no-chapters --no-attachments --no-track-tags --no-global-tags --subtitle-tracks 2 --forced-track 2:0 --default-track 2:1 --language 2:eng --track-name "2:" C:\Users\araz\Downloads\sample.mkv --title "Channel 4 HD" --ui-language en

mkvmerge v61.0.0 ('So') 64-bit
Error: The type of file 'C:\temp\sample_temp\ID1 -1763ms English.aac' could not be recognized.


   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 361
   at StaxRip.MkvMuxer.Mux() in D:\Code\Github\staxrip\staxrip\Source\General\Muxer.vb:line 627
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 378
```

**Comment by Patman86** [comment]
The snippet from your log file says something is wrong with the aac file.

**Comment by Godzilla-1225** [comment]
This is a consistent issue, not a one-off.

**Comment by Dendraspis** [comment]
Thanks for the good explanation and providing a short sample, it helped a lot. I could reproduce the problem and fix it. It will be available in the next release...
