### ISSUE TITLE
Python exception with StaxRip 2.11.0 only

### ISSUE THREAD

**Issue by maupassant2** [staxrip/staxrip#848]
Problem with StaxRip 2.11.0 only.

I tried to use the mClean VS filter and I received an error message 👍 
Script Error

Python exception: No attribute with the name vcm exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2242, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 2243, in vapoursynth.vpy_evaluateScript
  File "C:\1957\REQUESTS\THE AVENGERS\title_t00 (02)_temp\title_t00 (02)_new.vpy", line 46, in <module>
    clip = G41Fun.mClean(clip, thSAD=400, chroma=True, sharp=10, rn=14, deband=0, depth=0, strength=20)
  File "C:\STAXRIP\StaxRip-v2.11.0-x64\Apps\Plugins\VS\Scripts\G41Fun.py", line 2504, in mClean
    c = core.vcm.Median(clip, plane=[0, 1, 1]) if chroma else clip
  File "src\cython\vapoursynth.pyx", line 1891, in vapoursynth._CoreProxy.__getattr__
  File "src\cython\vapoursynth.pyx", line 1754, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name vcm exists. Did you mistype a plugin namespace?

**Comment by Dendraspis** [comment]
Thanks for the report.  🤝 
I fixed it and it will be available in the next release...
