### ISSUE TITLE
"No process is associated with this object" When Using NVEnc

### ISSUE THREAD

**Issue by ddelella** [staxrip/staxrip#948]
**Describe the bug**
When starting to encode a file using the NVEnc it fails with the message, "No process is associated with this object". This does not happen on all files I am converting but has been happening within the last week. I tried upgrading my NVEnc library but the same issue persists.

**Expected behavior**
The movie would encode using the NVEnc option.

**How to reproduce the issue**
Not sure if you need the exact file I have or if the specs in the log file are enough to figure out the issue. I have attached the MediaInfo.NET output as well.

**Provide information**

System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.WaitForExit(Int32 milliseconds)
   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 328
   at StaxRip.NVEnc.Encode() in D:\Code\Github\staxrip\staxrip\Source\Encoding\NVEnc.vb:line 107
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 371
   at StaxRip.GlobalClass.ProcessJobsRecursive() in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 232

[MovieNameHere_staxrip.log](https://github.com/staxrip/staxrip/files/9947109/MovieNameHere_staxrip.log)
[MovieNameHere-MediaInfo.txt](https://github.com/staxrip/staxrip/files/9947110/MovieNameHere-MediaInfo.txt)

**Comment by Dendraspis** [comment]
Regarding the error messages this should be hardware or OS related - maybe interfering app like AntiVirus.

Try to (temporary) disable your AntiVirus. You could also try checking and/or lowering this value:
![image](https://user-images.githubusercontent.com/50659978/224542340-47e069e5-196e-4128-a23c-47b1fbf48522.png)
